// AUTO-GENERATED by scripts/generate-knowledge.mjs — do not edit manually
// Source: ae-ai-starter/Scripts/verified/examples/ (5 examples)

export interface ExampleEntry {
  id: string;
  description: string;
  keywords: string[];
  script: string;
  notes?: string;
}

export const EXAMPLES: ExampleEntry[] = [
  {
    "id": "effect-manipulation",
    "description": "Add an effect, set multiple properties, and animate an effect property",
    "keywords": [
      "effect manipulation",
      "effect properties",
      "animate effect",
      "setvalueattime",
      "addproperty",
      "multiple properties"
    ],
    "script": "app.beginUndoGroup(\"Animate Effect Properties\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  var layer;\n  if (comp.selectedLayers.length > 0) {\n    layer = comp.selectedLayers[0];\n  } else {\n    layer = comp.layers.addSolid([0.2, 0.2, 0.2], \"Effect Target\", comp.width, comp.height, comp.pixelAspect, comp.duration);\n  }\n  var effects = layer.property(\"ADBE Effect Parade\");\n  var blur = effects.addProperty(\"ADBE Gaussian Blur 2\");\n  var blurriness = blur.property(\"ADBE Gaussian Blur 2-0001\");\n  blurriness.setValueAtTime(0, 0);\n  blurriness.setValueAtTime(1, 40);\n  blur.property(\"ADBE Gaussian Blur 2-0002\").setValue(1);\n  blur.property(\"ADBE Gaussian Blur 2-0003\").setValue(1);\n} finally {\n  app.endUndoGroup();\n}",
    "notes": "Use addProperty with the verified effect matchName, then access individual effect properties by verified property matchName."
  },
  {
    "id": "expression-on-property",
    "description": "Set an initial property value, then assign an expression string",
    "keywords": [
      "expression",
      "expressions",
      "property expression",
      "expression string",
      "expression engine",
      "wiggle"
    ],
    "script": "app.beginUndoGroup(\"Assign Expression\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  var layer = comp.layers.addSolid([0.15, 0.18, 0.24], \"Expression Opacity\", comp.width, comp.height, comp.pixelAspect, comp.duration);\n  var opacity = layer.property(\"ADBE Transform Group\").property(\"ADBE Opacity\");\n  opacity.setValue(80);\n  opacity.expression = \"var base = 80;\\nvar amount = 20;\\nbase + Math.sin(time * 6) * amount;\";\n  if (opacity.expressionError !== \"\") {\n    throw new Error(opacity.expressionError);\n  }\n} finally {\n  app.endUndoGroup();\n}",
    "notes": "Use setValue or setValueAtTime for script-side values. Assign expressions as strings to .expression, then check expressionError."
  },
  {
    "id": "keyframe-temporal-ease",
    "description": "Create keyframes and apply KeyframeEase with setTemporalEaseAtKey",
    "keywords": [
      "keyframe ease",
      "keyframeease",
      "temporal ease",
      "settemporaleaseatkey",
      "easing",
      "ease keyframes",
      "eased keyframes"
    ],
    "script": "app.beginUndoGroup(\"Ease Opacity Keyframes\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  var layer = comp.layers.addSolid([1, 0.45, 0.1], \"Eased Opacity\", comp.width, comp.height, comp.pixelAspect, comp.duration);\n  var opacity = layer.property(\"ADBE Transform Group\").property(\"ADBE Opacity\");\n  opacity.setValueAtTime(0, 0);\n  opacity.setValueAtTime(1, 100);\n  var easeIn = new KeyframeEase(0, 80);\n  var easeOut = new KeyframeEase(0, 80);\n  opacity.setTemporalEaseAtKey(1, [easeIn], [easeOut]);\n  opacity.setTemporalEaseAtKey(2, [easeIn], [easeOut]);\n} finally {\n  app.endUndoGroup();\n}",
    "notes": "setTemporalEaseAtKey takes arrays of KeyframeEase objects. One-dimensional properties use one ease object per side."
  },
  {
    "id": "text-layer-creation",
    "description": "Create a text layer and set font, size, fill color, and justification",
    "keywords": [
      "text layer",
      "addtext",
      "textdocument",
      "source text",
      "font",
      "font size",
      "fontsize",
      "fill color",
      "justification"
    ],
    "script": "app.beginUndoGroup(\"Create Text Layer\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  var textLayer = comp.layers.addText(\"Welcome\");\n  var textProp = textLayer.property(\"ADBE Text Properties\").property(\"ADBE Text Document\");\n  var textDoc = textProp.value;\n  textDoc.font = \"ArialMT\";\n  textDoc.fontSize = 48;\n  textDoc.applyFill = true;\n  textDoc.fillColor = [1, 1, 1];\n  textDoc.justification = ParagraphJustification.CENTER_JUSTIFY;\n  textProp.setValue(textDoc);\n  textLayer.property(\"ADBE Transform Group\").property(\"ADBE Anchor Point\").setValue([0, 0]);\n  textLayer.property(\"ADBE Transform Group\").property(\"ADBE Position\").setValue([comp.width / 2, comp.height / 2]);\n} finally {\n  app.endUndoGroup();\n}",
    "notes": "Read TextDocument with .value, mutate the local object, then write it back with .setValue(). Set applyFill before fillColor."
  },
  {
    "id": "trim-paths-animation",
    "description": "Animate Trim Paths Start and End on a shape layer",
    "keywords": [
      "trim paths",
      "trim path",
      "trim",
      "shape layer animation",
      "shape path",
      "vector trim",
      "start end"
    ],
    "script": "app.beginUndoGroup(\"Animate Trim Paths\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  var layer = comp.layers.addShape();\n  layer.name = \"Trim Paths Line\";\n  var contents = layer.property(\"ADBE Root Vectors Group\");\n  var group = contents.addProperty(\"ADBE Vector Group\");\n  group.name = \"Animated Line\";\n  var groupContents = group.property(\"ADBE Vectors Group\");\n  var rect = groupContents.addProperty(\"ADBE Vector Shape - Rect\");\n  rect.property(\"ADBE Vector Rect Size\").setValue([600, 180]);\n  rect.property(\"ADBE Vector Rect Position\").setValue([0, 0]);\n  var stroke = groupContents.addProperty(\"ADBE Vector Graphic - Stroke\");\n  stroke.property(\"ADBE Vector Stroke Color\").setValue([0.1, 0.8, 1, 1]);\n  stroke.property(\"ADBE Vector Stroke Width\").setValue(12);\n  var trim = groupContents.addProperty(\"ADBE Vector Filter - Trim\");\n  var startProp = trim.property(\"ADBE Vector Trim Start\");\n  var endProp = trim.property(\"ADBE Vector Trim End\");\n  startProp.setValueAtTime(0, 0);\n  startProp.setValueAtTime(2, 0);\n  endProp.setValueAtTime(0, 0);\n  endProp.setValueAtTime(2, 100);\n  layer.property(\"ADBE Transform Group\").property(\"ADBE Position\").setValue([comp.width / 2, comp.height / 2]);\n} finally {\n  app.endUndoGroup();\n}",
    "notes": "Add shape operators to ADBE Vectors Group, then keyframe ADBE Vector Trim Start and ADBE Vector Trim End on the Trim Paths operator."
  }
];

