// AUTO-GENERATED by scripts/generate-knowledge.mjs — do not edit manually
// Source: ae-ai-starter/Scripts/verified/examples/ (5 examples)

export interface ExampleEntry {
  id: string;
  description: string;
  keywords: string[];
  script: string;
  notes?: string;
}

export const EXAMPLES: ExampleEntry[] = [
  {
    "id": "effect-manipulation",
    "description": "Add an effect, set multiple properties, and animate an effect property",
    "keywords": [
      "effect manipulation",
      "effect properties",
      "animate effect",
      "setvalueattime",
      "addproperty",
      "multiple properties"
    ],
    "script": "app.beginUndoGroup(\"Animate Effect Properties\");\nvar comp = app.project.activeItem;\nif (!(comp instanceof CompItem)) {\n  throw new Error(\"Open a composition first.\");\n}\nvar layer;\nif (comp.selectedLayers.length > 0) {\n  layer = comp.selectedLayers[0];\n} else {\n  layer = comp.layers.addSolid([0.2, 0.2, 0.2], \"Effect Target\", comp.width, comp.height, comp.pixelAspect, comp.duration);\n}\nvar effects = layer.property(\"ADBE Effect Parade\");\nvar blur = effects.addProperty(\"ADBE Gaussian Blur 2\");\nvar blurriness = blur.property(\"ADBE Gaussian Blur 2-0001\");\nblurriness.setValueAtTime(comp.time, 0);\nblurriness.setValueAtTime(comp.time + 1, 40);\nblur.property(\"ADBE Gaussian Blur 2-0002\").setValue(1);\nblur.property(\"ADBE Gaussian Blur 2-0003\").setValue(1);\napp.endUndoGroup();",
    "notes": "Use addProperty with the verified effect matchName, then access individual effect properties by verified property matchName."
  },
  {
    "id": "expression-on-property",
    "description": "Set an initial property value, then assign an expression string",
    "keywords": [
      "expression",
      "expressions",
      "property expression",
      "expression string",
      "expression engine",
      "wiggle"
    ],
    "script": "app.beginUndoGroup(\"Assign Expression\");\nvar comp = app.project.activeItem;\nif (!(comp instanceof CompItem)) {\n  throw new Error(\"Open a composition first.\");\n}\nvar layer = comp.layers.addSolid([0.15, 0.18, 0.24], \"Expression Opacity\", comp.width, comp.height, comp.pixelAspect, comp.duration);\nvar opacity = layer.property(\"ADBE Transform Group\").property(\"ADBE Opacity\");\nopacity.setValue(80);\nopacity.expression = \"var base = 80;\\nvar amount = 20;\\nbase + Math.sin(time * 6) * amount;\";\nif (opacity.expressionError !== \"\") {\n  throw new Error(opacity.expressionError);\n}\napp.endUndoGroup();",
    "notes": "Use setValue or setValueAtTime for script-side values. Assign expressions as strings to .expression, then check expressionError."
  },
  {
    "id": "keyframe-temporal-ease",
    "description": "Create keyframes and apply KeyframeEase with setTemporalEaseAtKey",
    "keywords": [
      "keyframe ease",
      "keyframeease",
      "temporal ease",
      "settemporaleaseatkey",
      "easing",
      "ease keyframes",
      "eased keyframes"
    ],
    "script": "app.beginUndoGroup(\"Ease Opacity Keyframes\");\nvar comp = app.project.activeItem;\nif (!(comp instanceof CompItem)) {\n  throw new Error(\"Open a composition first.\");\n}\nvar layer = comp.layers.addSolid([1, 0.45, 0.1], \"Eased Opacity\", comp.width, comp.height, comp.pixelAspect, comp.duration);\nvar opacity = layer.property(\"ADBE Transform Group\").property(\"ADBE Opacity\");\nopacity.setValueAtTime(comp.time, 0);\nopacity.setValueAtTime(comp.time + 1, 100);\nvar easeIn = new KeyframeEase(0, 80);\nvar easeOut = new KeyframeEase(0, 80);\nopacity.setTemporalEaseAtKey(1, [easeIn], [easeOut]);\nopacity.setTemporalEaseAtKey(2, [easeIn], [easeOut]);\napp.endUndoGroup();",
    "notes": "setTemporalEaseAtKey takes arrays of KeyframeEase objects. One-dimensional properties use one ease object per side."
  },
  {
    "id": "text-layer-creation",
    "description": "Create a text layer and set font, size, fill color, and justification",
    "keywords": [
      "text layer",
      "addtext",
      "textdocument",
      "source text",
      "font",
      "font size",
      "fontsize",
      "fill color",
      "justification"
    ],
    "script": "app.beginUndoGroup(\"Create Text Layer\");\nvar comp = app.project.activeItem;\nif (!(comp instanceof CompItem)) {\n  throw new Error(\"Open a composition first.\");\n}\nvar textLayer = comp.layers.addText(\"Welcome\");\nvar textProp = textLayer.property(\"ADBE Text Properties\").property(\"ADBE Text Document\");\nvar textDoc = textProp.value;\ntextDoc.font = \"ArialMT\";\ntextDoc.fontSize = 48;\ntextDoc.applyFill = true;\ntextDoc.fillColor = [1, 1, 1];\ntextDoc.justification = ParagraphJustification.CENTER_JUSTIFY;\ntextProp.setValue(textDoc);\ntextLayer.property(\"ADBE Transform Group\").property(\"ADBE Anchor Point\").setValue([0, 0]);\ntextLayer.property(\"ADBE Transform Group\").property(\"ADBE Position\").setValue([comp.width / 2, comp.height / 2]);\napp.endUndoGroup();",
    "notes": "Read TextDocument with .value, mutate the local object, then write it back with .setValue(). Set applyFill before fillColor."
  },
  {
    "id": "trim-paths-animation",
    "description": "Animate Trim Paths Start and End on a shape layer",
    "keywords": [
      "trim paths",
      "trim path",
      "trim",
      "shape layer animation",
      "shape path",
      "vector trim",
      "start end"
    ],
    "script": "app.beginUndoGroup(\"Animate Trim Paths\");\nvar comp = app.project.activeItem;\nif (!(comp instanceof CompItem)) {\n  throw new Error(\"Open a composition first.\");\n}\nvar layer = comp.layers.addShape();\nlayer.name = \"Trim Paths Line\";\nvar contents = layer.property(\"ADBE Root Vectors Group\");\nvar group = contents.addProperty(\"ADBE Vector Group\");\ngroup.name = \"Animated Line\";\nvar groupContents = group.property(\"ADBE Vectors Group\");\nvar rect = groupContents.addProperty(\"ADBE Vector Shape - Rect\");\nrect.property(\"ADBE Vector Rect Size\").setValue([600, 180]);\nrect.property(\"ADBE Vector Rect Position\").setValue([0, 0]);\nvar stroke = groupContents.addProperty(\"ADBE Vector Graphic - Stroke\");\nstroke.property(\"ADBE Vector Stroke Color\").setValue([0.1, 0.8, 1, 1]);\nstroke.property(\"ADBE Vector Stroke Width\").setValue(12);\nvar trim = groupContents.addProperty(\"ADBE Vector Filter - Trim\");\nvar startProp = trim.property(\"ADBE Vector Trim Start\");\nvar endProp = trim.property(\"ADBE Vector Trim End\");\nstartProp.setValueAtTime(comp.time, 0);\nstartProp.setValueAtTime(comp.time + 2, 0);\nendProp.setValueAtTime(comp.time, 0);\nendProp.setValueAtTime(comp.time + 2, 100);\nlayer.property(\"ADBE Transform Group\").property(\"ADBE Position\").setValue([comp.width / 2, comp.height / 2]);\napp.endUndoGroup();",
    "notes": "Add shape operators to ADBE Vectors Group, then keyframe ADBE Vector Trim Start and ADBE Vector Trim End on the Trim Paths operator."
  }
];

