// AUTO-GENERATED by scripts/generate-knowledge.mjs — do not edit manually
// Source: ae-ai-starter/Scripts/verified/properties/global-enums.json

export const GLOBAL_ENUMS: Record<string, Record<string, number | string>> = {};
