// AUTO-GENERATED by scripts/generate-knowledge.mjs — do not edit manually
// Source: recipes (37 recipes)

export interface RecipeEntry {
  id: string;
  description: string;
  keywords: string[];
  script: string;
  terms: string[];
  verifiedStatus: "verified" | "pending";
  notes?: string;
}

export const RECIPES: RecipeEntry[] = [
  {
    "id": "bounce-overshoot-expression",
    "description": "Add a damped bounce overshoot expression after the last keyframe on selected numeric properties.",
    "keywords": [
      "bounce expression",
      "overshoot expression",
      "damped bounce",
      "keyframe bounce"
    ],
    "script": "app.beginUndoGroup(\"Bounce Overshoot\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem) || comp.selectedProperties.length < 1) throw new Error(\"Select a keyframed property.\");\n  for (var i = 0; i < comp.selectedProperties.length; i++) {\n    var prop = comp.selectedProperties[i];\n    if (prop instanceof Property && prop.canSetExpression) {\n      prop.expression = \"var amp = 0.08;\\nvar freq = 3;\\nvar decay = 5;\\nif (numKeys < 1 || time <= key(numKeys).time) value;\\nelse {\\n  var t = time - key(numKeys).time;\\n  var v = velocityAtTime(key(numKeys).time - thisComp.frameDuration / 10);\\n  value + v * amp * Math.sin(freq * t * 2 * Math.PI) / Math.exp(decay * t);\\n}\";\n    }\n  }\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "damped",
      "bounce",
      "overshoot",
      "expression",
      "after",
      "last",
      "keyframe",
      "numeric",
      "properties"
    ],
    "verifiedStatus": "verified",
    "notes": "Uses verified key(), velocityAtTime(), and thisComp.frameDuration references."
  },
  {
    "id": "expression-follow-delay",
    "description": "Make the second selected layer follow the first selected layer Position with a configurable time delay expression.",
    "keywords": [
      "follow delay",
      "delayed follow",
      "position delay",
      "trailing layer",
      "time delay"
    ],
    "script": "app.beginUndoGroup(\"Follow With Delay\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem) || comp.selectedLayers.length < 2) throw new Error(\"Select leader then follower layers.\");\n  var leader = comp.selectedLayers[0];\n  var follower = comp.selectedLayers[1];\n  var delay = follower.property(\"ADBE Effect Parade\").addProperty(\"ADBE Slider Control\");\n  delay.name = \"Follow Delay\";\n  delay.property(1).setValue(0.15);\n  function quoteLayerName(value) {\n    var result = \"\";\n    for (var i = 0; i < value.length; i++) {\n      var ch = value.charAt(i);\n      if (ch === \"\\\\\" || ch === \"'\") result += \"\\\\\";\n      result += ch;\n    }\n    return result;\n  }\n  var escaped = quoteLayerName(leader.name);\n  var position = follower.property(\"ADBE Transform Group\").property(\"ADBE Position\");\n  position.expression = \"var d = effect('Follow Delay')('Slider');\\nthisComp.layer('\" + escaped + \"').transform.position.valueAtTime(time - d);\";\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "second",
      "follow",
      "first",
      "position",
      "configurable",
      "time",
      "delay",
      "expression",
      "delayed",
      "trailing"
    ],
    "verifiedStatus": "verified",
    "notes": "Uses the verified valueAtTime() method."
  },
  {
    "id": "expression-on-property",
    "description": "Set an initial property value, then assign an expression string",
    "keywords": [
      "expression",
      "expressions",
      "property expression",
      "expression string",
      "expression engine",
      "wiggle"
    ],
    "script": "app.beginUndoGroup(\"Assign Expression\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  var layer = comp.layers.addSolid([0.15, 0.18, 0.24], \"Expression Opacity\", comp.width, comp.height, comp.pixelAspect, comp.duration);\n  var opacity = layer.property(\"ADBE Transform Group\").property(\"ADBE Opacity\");\n  opacity.setValue(80);\n  opacity.expression = \"var base = 80;\\nvar amount = 20;\\nbase + Math.sin(time * 6) * amount;\";\n  if (opacity.expressionError !== \"\") {\n    throw new Error(opacity.expressionError);\n  }\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "initial",
      "property",
      "value",
      "then",
      "assign",
      "expression",
      "string",
      "expressions",
      "engine",
      "wiggle"
    ],
    "verifiedStatus": "verified",
    "notes": "Use setValue or setValueAtTime for script-side values. Assign expressions as strings to .expression, then check expressionError."
  },
  {
    "id": "loop-keyframes",
    "description": "Loop the selected keyframed properties with a cycle loopOut expression and guard properties with fewer than two keys.",
    "keywords": [
      "loop keyframes",
      "loopout",
      "cycle animation",
      "repeat keyframes"
    ],
    "script": "app.beginUndoGroup(\"Loop Keyframes\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem) || comp.selectedProperties.length < 1) throw new Error(\"Select at least one property.\");\n  for (var i = 0; i < comp.selectedProperties.length; i++) {\n    var prop = comp.selectedProperties[i];\n    if (prop instanceof Property && prop.canSetExpression) {\n      prop.expression = \"numKeys >= 2 ? loopOut('cycle') : value;\";\n    }\n  }\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "loop",
      "keyframed",
      "properties",
      "cycle",
      "loopout",
      "expression",
      "guard",
      "fewer",
      "than",
      "keys",
      "keyframes",
      "animation",
      "repeat"
    ],
    "verifiedStatus": "verified",
    "notes": "The numKeys guard covers the verified loopOut() two-key requirement."
  },
  {
    "id": "time-remap-enable",
    "description": "Enable Time Remapping on a layer and add keyframes to remap source time",
    "keywords": [
      "time remap",
      "timeremapenabled",
      "time remapping",
      "retime",
      "speed ramp",
      "adbe time remapping",
      "source time"
    ],
    "script": "app.beginUndoGroup(\"Enable Time Remap\");\ntry {\n  var comp = app.project.activeItem;\n  if (!comp || !(comp instanceof CompItem)) {\n    throw new Error(\"Please select a composition.\");\n  }\n  if (comp.selectedLayers.length === 0) {\n    throw new Error(\"Select a layer.\");\n  }\n  var layer = comp.selectedLayers[0];\n  layer.timeRemapEnabled = true;\n  var timeRemap = layer.property(\"ADBE Time Remapping\");\n  // AE auto-creates 2 keyframes when enabling: at layer.inPoint and layer.outPoint.\n  // keyValue is source-time in seconds (where in the source to sample),\n  // NOT comp-time.\n  // Read auto-created keyframes before adding new ones:\n  var autoKeyCount = timeRemap.numKeys;\n  // Example: hold on frame 0 until 1s, then play from frame 0 again at 2s\n  // timeRemap.setValueAtTime(0, 0);      // comp 0s -> source 0s\n  // timeRemap.setValueAtTime(1.0, 0);    // comp 1s -> still source 0s (hold)\n  // timeRemap.setValueAtTime(2.0, 1.0);  // comp 2s -> source 1s\n} catch (e) {\n  alert(\"Error: \" + e.toString());\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "enable",
      "time",
      "remapping",
      "keyframes",
      "remap",
      "source",
      "timeremapenabled",
      "retime",
      "speed",
      "ramp",
      "adbe"
    ],
    "verifiedStatus": "verified",
    "notes": "When timeRemapEnabled is first set to true, AE automatically creates two keyframes: one at layer.inPoint (value=0) and one at layer.outPoint (value=source duration). Time Remap values are source-time seconds — where in the source footage to sample — not comp-time positions. Always read the auto-created keyframes before adding more to avoid conflicts."
  },
  {
    "id": "wiggle-with-slider-controls",
    "description": "Add Frequency and Amount slider controls and drive the selected layer Position with a wiggle expression.",
    "keywords": [
      "wiggle controls",
      "wiggle slider",
      "frequency slider",
      "amount slider"
    ],
    "script": "app.beginUndoGroup(\"Wiggle With Controls\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem) || comp.selectedLayers.length < 1) throw new Error(\"Select a layer.\");\n  var layer = comp.selectedLayers[0];\n  var effects = layer.property(\"ADBE Effect Parade\");\n  var frequency = effects.addProperty(\"ADBE Slider Control\");\n  frequency.name = \"Wiggle Frequency\";\n  frequency.property(1).setValue(2);\n  var amount = effects.addProperty(\"ADBE Slider Control\");\n  amount.name = \"Wiggle Amount\";\n  amount.property(1).setValue(50);\n  var position = layer.property(\"ADBE Transform Group\").property(\"ADBE Position\");\n  position.expression = \"var f = effect('Wiggle Frequency')('Slider');\\nvar a = effect('Wiggle Amount')('Slider');\\nwiggle(f, a);\";\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "frequency",
      "amount",
      "slider",
      "controls",
      "drive",
      "position",
      "wiggle",
      "expression"
    ],
    "verifiedStatus": "verified",
    "notes": "Uses the verified wiggle() signature and Slider Control matchName."
  },
  {
    "id": "add-light-3d-setup",
    "description": "Create a 3D point light and enable 3D plus light acceptance on selected AV layers.",
    "keywords": [
      "add light",
      "3d light",
      "point light",
      "light setup"
    ],
    "script": "app.beginUndoGroup(\"3D Light Setup\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) throw new Error(\"Open a composition.\");\n  for (var i = 0; i < comp.selectedLayers.length; i++) {\n    try { comp.selectedLayers[i].threeDLayer = true; } catch (e) {}\n  }\n  var light = comp.layers.addLight(\"Key Light\", [comp.width * 0.35, comp.height * 0.3]);\n  light.lightType = LightType.POINT;\n  light.property(\"ADBE Transform Group\").property(\"ADBE Position\").setValue([comp.width * 0.35, comp.height * 0.3, -500]);\n  light.property(\"ADBE Light Options Group\").property(\"ADBE Light Intensity\").setValue(100);\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "create",
      "point",
      "light",
      "enable",
      "plus",
      "acceptance",
      "setup"
    ],
    "verifiedStatus": "verified",
    "notes": "LightType values are discovered by discover_global_enums.jsx."
  },
  {
    "id": "camera-orbit-null-rig",
    "description": "Create a two-node camera parented to a centered 3D null for an orbit rig.",
    "keywords": [
      "camera orbit",
      "camera rig",
      "orbit null",
      "two node camera"
    ],
    "script": "app.beginUndoGroup(\"Camera Orbit Rig\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) throw new Error(\"Open a composition.\");\n  var rig = comp.layers.addNull(comp.duration);\n  rig.name = \"Camera Orbit\";\n  rig.threeDLayer = true;\n  rig.property(\"ADBE Transform Group\").property(\"ADBE Position\").setValue([comp.width / 2, comp.height / 2, 0]);\n  var camera = comp.layers.addCamera(\"Orbit Camera\", [comp.width / 2, comp.height / 2]);\n  camera.property(\"ADBE Transform Group\").property(\"ADBE Position\").setValue([comp.width / 2, comp.height / 2, -1500]);\n  camera.setParentWithJump(rig);\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "create",
      "node",
      "camera",
      "parented",
      "centered",
      "null",
      "orbit",
      "rig"
    ],
    "verifiedStatus": "verified",
    "notes": "Uses full Transform property paths."
  },
  {
    "id": "duplicate-composition",
    "description": "Duplicate composition with deep copy to fully decouple nested comps",
    "keywords": [
      "duplicate composition",
      "duplicate comp",
      "copy composition",
      "deep copy comp",
      "replacesource",
      "nested comp",
      "clone composition"
    ],
    "script": "app.beginUndoGroup(\"Duplicate Composition\");\ntry {\n  var comp = app.project.activeItem;\n  if (!comp || !(comp instanceof CompItem)) {\n    throw new Error(\"Please select a composition.\");\n  }\n  // Shallow duplicate: nested comps remain shared references.\n  // Use deepDuplicateComp for a fully decoupled copy.\n  var compMap = {};\n  var result = deepDuplicateComp(comp, compMap);\n  result.name = comp.name + \" copy\";\n  alert(\"Created: \" + result.name);\n} catch (e) {\n  alert(\"Error: \" + e.toString());\n} finally {\n  app.endUndoGroup();\n}\n\nfunction deepDuplicateComp(comp, compMap) {\n  if (compMap[comp.id]) return compMap[comp.id];\n  var dup = comp.duplicate();\n  compMap[comp.id] = dup;\n  var i;\n  for (i = 1; i <= dup.numLayers; i++) {\n    var layer = dup.layer(i);\n    if (layer.source && layer.source instanceof CompItem) {\n      layer.replaceSource(deepDuplicateComp(layer.source, compMap), false);\n    }\n  }\n  return dup;\n}",
    "terms": [
      "duplicate",
      "composition",
      "deep",
      "copy",
      "fully",
      "decouple",
      "nested",
      "comps",
      "comp",
      "replacesource",
      "clone"
    ],
    "verifiedStatus": "verified",
    "notes": "comp.duplicate() is a shallow copy — nested comps inside remain shared references. Editing a nested comp affects both the original and the duplicate. deepDuplicateComp recursively duplicates each nested CompItem and uses replaceSource(newComp, false) to redirect layers. compMap keyed by comp.id prevents infinite recursion on shared nested comps."
  },
  {
    "id": "precompose-selected-layers",
    "description": "Pre-compose the currently selected layers into a new comp",
    "keywords": [
      "precompose",
      "pre-compose",
      "pre compose",
      "nest layers",
      "nest into comp",
      "group layers",
      "precomp"
    ],
    "script": "app.beginUndoGroup(\"Pre-compose Selected Layers\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  if (comp.selectedLayers.length === 0) {\n    throw new Error(\"Select at least one layer to pre-compose.\");\n  }\n  // Collect 1-based integer indices -- precompose() does NOT accept Layer objects.\n  var indices = [];\n  var i;\n  for (i = 0; i < comp.selectedLayers.length; i++) {\n    indices.push(comp.selectedLayers[i].index);\n  }\n  // Sort ascending -- precompose expects a sorted index array.\n  indices.sort(function(a, b) { return a - b; });\n  var newCompName = \"Precomp\";\n  // moveAllAttributes=true (the default) moves all layer attributes into the new comp.\n  // Set to false only when pre-composing a single layer and you want to keep attributes.\n  var newComp = comp.layers.precompose(indices, newCompName, true);\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "pre",
      "compose",
      "currently",
      "comp",
      "precompose",
      "nest",
      "group",
      "precomp"
    ],
    "verifiedStatus": "verified",
    "notes": "precompose() takes an array of 1-based integer indices, NOT Layer objects. moveAllAttributes defaults to true; setting it to false is only valid when the array has exactly one index. Returns the new CompItem."
  },
  {
    "id": "effect-manipulation",
    "description": "Add an effect, set multiple properties, and animate an effect property",
    "keywords": [
      "effect manipulation",
      "effect properties",
      "animate effect",
      "setvalueattime",
      "addproperty",
      "multiple properties"
    ],
    "script": "app.beginUndoGroup(\"Animate Effect Properties\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  var layer;\n  if (comp.selectedLayers.length > 0) {\n    layer = comp.selectedLayers[0];\n  } else {\n    layer = comp.layers.addSolid([0.2, 0.2, 0.2], \"Effect Target\", comp.width, comp.height, comp.pixelAspect, comp.duration);\n  }\n  var effects = layer.property(\"ADBE Effect Parade\");\n  var blur = effects.addProperty(\"ADBE Gaussian Blur 2\");\n  var blurriness = blur.property(\"ADBE Gaussian Blur 2-0001\");\n  blurriness.setValueAtTime(0, 0);\n  blurriness.setValueAtTime(1, 40);\n  blur.property(\"ADBE Gaussian Blur 2-0002\").setValue(1);\n  blur.property(\"ADBE Gaussian Blur 2-0003\").setValue(1);\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "multiple",
      "properties",
      "animate",
      "property",
      "manipulation",
      "setvalueattime",
      "addproperty"
    ],
    "verifiedStatus": "verified",
    "notes": "Use addProperty with the verified effect matchName, then access individual effect properties by verified property matchName."
  },
  {
    "id": "glow-treatment-stack",
    "description": "Add a verified Glow effect treatment to selected layers with practical threshold, radius, and intensity values.",
    "keywords": [
      "glow treatment",
      "glow stack",
      "neon glow",
      "add glow"
    ],
    "script": "app.beginUndoGroup(\"Glow Treatment\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem) || comp.selectedLayers.length < 1) throw new Error(\"Select at least one layer.\");\n  for (var i = 0; i < comp.selectedLayers.length; i++) {\n    var effects = comp.selectedLayers[i].property(\"ADBE Effect Parade\");\n    var glow = effects.addProperty(\"ADBE Glo2\");\n    glow.property(\"ADBE Glo2-0002\").setValue(55);\n    glow.property(\"ADBE Glo2-0003\").setValue(35);\n    glow.property(\"ADBE Glo2-0004\").setValue(1.2);\n  }\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "verified",
      "glow",
      "treatment",
      "practical",
      "threshold",
      "radius",
      "intensity",
      "values",
      "stack",
      "neon"
    ],
    "verifiedStatus": "verified",
    "notes": "Uses the verified Glow effect and property matchNames."
  },
  {
    "id": "copy-keyframes",
    "description": "Copy keyframes from one property to another",
    "keywords": [
      "copy keyframes",
      "copy keys",
      "keyframe copy",
      "transfer keyframes",
      "paste keyframes",
      "duplicate keyframes"
    ],
    "script": "app.beginUndoGroup(\"Copy Keyframes\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  if (comp.selectedLayers.length < 1) {\n    throw new Error(\"Select at least one layer.\");\n  }\n  var layer = comp.selectedLayers[0];\n  var srcProp = layer.property(\"ADBE Transform Group\").property(\"ADBE Opacity\");\n  var dstProp = layer.property(\"ADBE Transform Group\").property(\"ADBE Opacity\");\n  // Replace srcProp and dstProp with the actual source and destination properties.\n  // Both properties must exist on accessible layers in the composition.\n  var keyCount = srcProp.numKeys;\n  if (keyCount === 0) {\n    throw new Error(\"Source property has no keyframes.\");\n  }\n  // Snapshot all keyframe data before modifying anything.\n  var snapTimes = [];\n  var snapValues = [];\n  var snapInEase = [];\n  var snapOutEase = [];\n  var i;\n  for (i = 1; i <= keyCount; i++) {\n    snapTimes.push(srcProp.keyTime(i));\n    snapValues.push(srcProp.keyValue(i));\n    snapInEase.push(srcProp.keyInTemporalEase(i));\n    snapOutEase.push(srcProp.keyOutTemporalEase(i));\n  }\n  // Write keyframes to destination, then apply ease.\n  for (i = 0; i < keyCount; i++) {\n    dstProp.setValueAtTime(snapTimes[i], snapValues[i]);\n  }\n  for (i = 0; i < keyCount; i++) {\n    dstProp.setTemporalEaseAtKey(i + 1, snapInEase[i], snapOutEase[i]);\n  }\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "copy",
      "keyframes",
      "property",
      "another",
      "keys",
      "keyframe",
      "transfer",
      "paste",
      "duplicate"
    ],
    "verifiedStatus": "verified",
    "notes": "There is no native copyKeyframes() API. Always snapshot all keyframe data into arrays first, then write setValueAtTime, then re-apply ease — setting ease changes key indices, so re-apply in a second pass. Spatial properties also need setSpatialTangentsAtKey after the ease pass."
  },
  {
    "id": "easy-ease-preset",
    "description": "Apply temporal Bezier interpolation and an Easy Ease influence preset to every key on selected properties.",
    "keywords": [
      "easy ease",
      "keyframe ease preset",
      "temporal ease",
      "bezier keyframes"
    ],
    "script": "app.beginUndoGroup(\"Easy Ease Preset\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem) || comp.selectedProperties.length < 1) throw new Error(\"Select keyframed properties.\");\n  for (var i = 0; i < comp.selectedProperties.length; i++) {\n    var prop = comp.selectedProperties[i];\n    if (!(prop instanceof Property) || prop.numKeys < 1) continue;\n    var isSpatial = prop.propertyValueType === PropertyValueType.TwoD_SPATIAL || prop.propertyValueType === PropertyValueType.ThreeD_SPATIAL;\n    var dimensions = isSpatial ? 1 : (prop.value instanceof Array ? prop.value.length : 1);\n    var easeIn = [];\n    var easeOut = [];\n    for (var d = 0; d < dimensions; d++) {\n      easeIn.push(new KeyframeEase(0, 33.333));\n      easeOut.push(new KeyframeEase(0, 33.333));\n    }\n    for (var k = 1; k <= prop.numKeys; k++) {\n      prop.setInterpolationTypeAtKey(k, KeyframeInterpolationType.BEZIER, KeyframeInterpolationType.BEZIER);\n      prop.setTemporalEaseAtKey(k, easeIn, easeOut);\n    }\n  }\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "apply",
      "temporal",
      "bezier",
      "interpolation",
      "easy",
      "ease",
      "influence",
      "preset",
      "every",
      "key",
      "properties",
      "keyframe",
      "keyframes"
    ],
    "verifiedStatus": "verified",
    "notes": "KeyframeInterpolationType values are discovered by discover_global_enums.jsx."
  },
  {
    "id": "keyframe-temporal-ease",
    "description": "Create keyframes and apply KeyframeEase with setTemporalEaseAtKey",
    "keywords": [
      "keyframe ease",
      "keyframeease",
      "temporal ease",
      "settemporaleaseatkey",
      "easing",
      "ease keyframes",
      "eased keyframes"
    ],
    "script": "app.beginUndoGroup(\"Ease Opacity and Position Keyframes\");\ntry {\n  function easeArray(prop, speed, influence) {\n    var n = prop.isSpatial ? 1 : (prop.value instanceof Array ? prop.value.length : 1);\n    var arr = [];\n    for (var i = 0; i < n; i++) arr.push(new KeyframeEase(speed, influence));\n    return arr;\n  }\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  var layer = comp.layers.addSolid([1, 0.45, 0.1], \"Eased Layer\", comp.width, comp.height, comp.pixelAspect, comp.duration);\n  var transform = layer.property(\"ADBE Transform Group\");\n  var opacity = transform.property(\"ADBE Opacity\");\n  var position = transform.property(\"ADBE Position\");\n  opacity.setValueAtTime(0, 0);\n  opacity.setValueAtTime(1, 100);\n  position.setValueAtTime(0, [comp.width / 2 - 200, comp.height / 2]);\n  position.setValueAtTime(1, [comp.width / 2, comp.height / 2]);\n  var opacityEaseIn = easeArray(opacity, 0, 80);\n  var opacityEaseOut = easeArray(opacity, 0, 80);\n  var positionEaseIn = easeArray(position, 0, 80);\n  var positionEaseOut = easeArray(position, 0, 80);\n  opacity.setTemporalEaseAtKey(1, opacityEaseIn, opacityEaseOut);\n  opacity.setTemporalEaseAtKey(2, opacityEaseIn, opacityEaseOut);\n  position.setTemporalEaseAtKey(1, positionEaseIn, positionEaseOut);\n  position.setTemporalEaseAtKey(2, positionEaseIn, positionEaseOut);\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "create",
      "keyframes",
      "apply",
      "keyframeease",
      "settemporaleaseatkey",
      "keyframe",
      "ease",
      "temporal",
      "easing",
      "eased"
    ],
    "verifiedStatus": "verified",
    "notes": "setTemporalEaseAtKey takes one KeyframeEase per value dimension in each in/out array. Spatial properties such as Position and Anchor Point take exactly one KeyframeEase per side regardless of dimensions."
  },
  {
    "id": "reverse-keyframes",
    "description": "Reverse keyframes on a property by snapshotting then rewriting in reverse order",
    "keywords": [
      "reverse keyframes",
      "flip keyframes",
      "reverse animation",
      "invert keyframes",
      "time-reverse keyframes",
      "backward animation"
    ],
    "script": "app.beginUndoGroup(\"Reverse Keyframes\");\ntry {\n  var comp = app.project.activeItem;\n  if (!comp || !(comp instanceof CompItem)) {\n    throw new Error(\"Please select a composition.\");\n  }\n  if (comp.selectedLayers.length === 0) {\n    throw new Error(\"Select a layer.\");\n  }\n  var layer = comp.selectedLayers[0];\n  // Replace with the actual property path to reverse.\n  var prop = layer.property(\"ADBE Transform Group\").property(\"ADBE Position\");\n  var keyCount = prop.numKeys;\n  if (keyCount < 2) {\n    throw new Error(\"Property needs at least 2 keyframes to reverse.\");\n  }\n  // Snapshot everything before touching keyframes.\n  var i;\n  var snapTimes = [];\n  var snapValues = [];\n  var snapInEase = [];\n  var snapOutEase = [];\n  var snapInInterp = [];\n  var snapOutInterp = [];\n  for (i = 1; i <= keyCount; i++) {\n    snapTimes.push(prop.keyTime(i));\n    snapValues.push(prop.keyValue(i));\n    snapInEase.push(prop.keyInTemporalEase(i));\n    snapOutEase.push(prop.keyOutTemporalEase(i));\n    snapInInterp.push(prop.keyInInterpolationType(i));\n    snapOutInterp.push(prop.keyOutInterpolationType(i));\n  }\n  // Delete all keys from highest index down (renumbering safe).\n  for (i = keyCount; i >= 1; i--) {\n    prop.removeKey(i);\n  }\n  // Rewrite in reverse: original last key maps to original first time.\n  for (i = 0; i < keyCount; i++) {\n    var srcIdx = keyCount - 1 - i; // reversed source index\n    prop.setValueAtTime(snapTimes[i], snapValues[srcIdx]);\n  }\n  // Reapply eases with in/out swapped.\n  for (i = 1; i <= keyCount; i++) {\n    var srcIdx2 = keyCount - i; // reversed source index (0-based)\n    prop.setTemporalEaseAtKey(\n      i,\n      snapOutEase[srcIdx2], // original outEase becomes inEase\n      snapInEase[srcIdx2]   // original inEase becomes outEase\n    );\n  }\n} catch (e) {\n  alert(\"Error: \" + e.toString());\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "reverse",
      "keyframes",
      "property",
      "snapshotting",
      "then",
      "rewriting",
      "order",
      "flip",
      "animation",
      "invert",
      "time",
      "backward"
    ],
    "verifiedStatus": "verified",
    "notes": "There is no native reverseKeyframes() API. Always delete keys from highest index downward — removeKey() renumbers all higher indices immediately. When rebuilding reversed keyframes, easeIn and easeOut swap roles: the original keyOutTemporalEase becomes the new keyInTemporalEase at the reversed position. Spatial properties also need setSpatialTangentsAtKey with tangents reversed."
  },
  {
    "id": "spatial-tangent-ease",
    "description": "Set spatial ease on Position keyframes for a curved motion path",
    "keywords": [
      "spatial ease",
      "spatial tangent",
      "curved path",
      "motion path",
      "bezier path",
      "position ease",
      "setspatialatkey",
      "setspatial"
    ],
    "script": "app.beginUndoGroup(\"Set Spatial Ease on Position\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  if (comp.selectedLayers.length < 1) {\n    throw new Error(\"Select a layer.\");\n  }\n  var layer = comp.selectedLayers[0];\n  var position = layer.property(\"ADBE Transform Group\").property(\"ADBE Position\");\n  // Create at least two position keyframes first.\n  var cx = comp.width / 2;\n  var cy = comp.height / 2;\n  position.setValueAtTime(0, [cx - 300, cy]);\n  position.setValueAtTime(1, [cx, cy - 200]);\n  position.setValueAtTime(2, [cx + 300, cy]);\n  // setSpatialTangentsAtKey only works on spatial (TwoD_SPATIAL / ThreeD_SPATIAL) properties.\n  // It does NOT work on Scale, Opacity, or other non-spatial properties.\n  // Disable auto-bezier and continuous bezier so AE does not override the tangents.\n  var keyIndex;\n  for (keyIndex = 1; keyIndex <= position.numKeys; keyIndex++) {\n    position.setSpatialAutoBezierAtKey(keyIndex, false);\n    position.setSpatialContinuousAtKey(keyIndex, false);\n    // inTangent and outTangent are [x, y] pixel offsets from the keyframe anchor.\n    position.setSpatialTangentsAtKey(keyIndex, [-100, 0], [100, 0]);\n  }\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "spatial",
      "ease",
      "position",
      "keyframes",
      "curved",
      "motion",
      "path",
      "tangent",
      "bezier",
      "setspatialatkey",
      "setspatial"
    ],
    "verifiedStatus": "verified",
    "notes": "setSpatialTangentsAtKey only works on TwoD_SPATIAL or ThreeD_SPATIAL properties (e.g. Position) — calling it on Scale or Opacity throws. Always call setSpatialAutoBezierAtKey(keyIndex, false) and setSpatialContinuousAtKey(keyIndex, false) first, otherwise AE overrides your tangents on the next frame render."
  },
  {
    "id": "copy-layer-between-comps",
    "description": "Copy layer to comp preserving all properties and keyframes",
    "keywords": [
      "copy layer to comp",
      "copytocomp",
      "move layer between comps",
      "duplicate layer to composition",
      "copy layer another comp"
    ],
    "script": "app.beginUndoGroup(\"Copy Layer to Comp\");\ntry {\n  var srcComp = app.project.activeItem;\n  if (!srcComp || !(srcComp instanceof CompItem)) {\n    throw new Error(\"Please select the source composition.\");\n  }\n  if (srcComp.selectedLayers.length === 0) {\n    throw new Error(\"Select a layer to copy.\");\n  }\n  var layer = srcComp.selectedLayers[0];\n  // Find target comp by name.\n  var targetComp = null;\n  var i;\n  for (i = 1; i <= app.project.numItems; i++) {\n    var item = app.project.item(i);\n    if (item instanceof CompItem && item.name === \"Target Comp Name\") {\n      targetComp = item;\n      break;\n    }\n  }\n  if (!targetComp) {\n    throw new Error(\"Target composition not found.\");\n  }\n  // copyToComp returns undefined, not the new layer.\n  // The copy becomes targetComp.layer(1) immediately after the call.\n  layer.copyToComp(targetComp);\n  var newLayer = targetComp.layer(1);\n} catch (e) {\n  alert(\"Error: \" + e.toString());\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "copy",
      "comp",
      "preserving",
      "properties",
      "keyframes",
      "copytocomp",
      "move",
      "comps",
      "duplicate",
      "composition",
      "another"
    ],
    "verifiedStatus": "verified",
    "notes": "copyToComp(targetComp) copies a layer with all properties, keyframes, and effects. It returns undefined — not the new layer. The copy is always inserted at index 1 (top of the stack) in the target comp. To reference the new layer immediately, use targetComp.layer(1) right after the call. The original layer is unchanged."
  },
  {
    "id": "duplicate-layer-offset",
    "description": "Duplicate a layer and offset the copy in comp time",
    "keywords": [
      "duplicate layer",
      "duplicate",
      "layer offset",
      "offset in time",
      "stagger",
      "starttime",
      "layer copy"
    ],
    "script": "app.beginUndoGroup(\"Duplicate and Offset Layer\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  if (comp.selectedLayers.length < 1) {\n    throw new Error(\"Select a layer to duplicate.\");\n  }\n  var original = comp.selectedLayers[0];\n  // duplicate() inserts the copy at index 1 (top of stack).\n  var copy = original.duplicate();\n  copy.name = original.name + \" copy\";\n  // startTime slides the whole layer bar in comp time (not a trim handle).\n  // .inPoint and .outPoint are trim positions -- distinct from startTime.\n  var offsetSeconds = 0.5;\n  copy.startTime = original.startTime + offsetSeconds;\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "duplicate",
      "offset",
      "copy",
      "comp",
      "time",
      "stagger",
      "starttime"
    ],
    "verifiedStatus": "verified",
    "notes": "duplicate() always inserts the new layer at index 1. Use .startTime to slide the layer bar in comp time; do NOT confuse with .inPoint/.outPoint which are trim handles on the source."
  },
  {
    "id": "parent-layer-by-name",
    "description": "Parent one layer to another by name without a transform jump",
    "keywords": [
      "parent layer",
      "parent",
      "parenting",
      "layer parent",
      "setparentwithjump",
      "parent by name",
      "null parent"
    ],
    "script": "app.beginUndoGroup(\"Parent Layer by Name\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  var childName = \"Title\";\n  var parentName = \"Background Box\";\n  var child = comp.layer(childName);\n  if (!child) {\n    throw new Error(\"Layer not found: \" + childName);\n  }\n  var parent = comp.layer(parentName);\n  if (!parent) {\n    throw new Error(\"Layer not found: \" + parentName);\n  }\n  // Assigning .parent compensates transforms so the layer does not jump visually.\n  // Use setParentWithJump(parent) if you want to preserve the raw transform values\n  // and intentionally accept the visual snap (e.g. locking values before rigging).\n  child.parent = parent;\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "parent",
      "another",
      "name",
      "without",
      "transform",
      "jump",
      "parenting",
      "setparentwithjump",
      "null"
    ],
    "verifiedStatus": "verified",
    "notes": "layer.parent = target auto-calculates a transform offset to prevent a visual jump. setParentWithJump(target) preserves the raw values and snaps visually — pick deliberately based on whether you want the child to stay in place or keep its current numeric values."
  },
  {
    "id": "track-matte-setup",
    "description": "Use the first selected layer as an alpha track matte for the second selected layer with the AE 23 setTrackMatte API.",
    "keywords": [
      "track matte",
      "alpha matte",
      "settrackmatte",
      "matte setup"
    ],
    "script": "app.beginUndoGroup(\"Track Matte Setup\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem) || comp.selectedLayers.length < 2) throw new Error(\"Select matte then fill layers.\");\n  var matte = comp.selectedLayers[0];\n  var fill = comp.selectedLayers[1];\n  if (typeof fill.setTrackMatte !== \"function\") throw new Error(\"setTrackMatte requires After Effects 23 or newer.\");\n  fill.setTrackMatte(matte, TrackMatteType.ALPHA);\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "first",
      "alpha",
      "track",
      "matte",
      "second",
      "settrackmatte",
      "api",
      "setup"
    ],
    "verifiedStatus": "verified",
    "notes": "Requires AE 23+. TrackMatteType values are discovered by discover_global_enums.jsx."
  },
  {
    "id": "import-file",
    "description": "Import file into the project as Footage",
    "keywords": [
      "import file",
      "importfile",
      "import footage",
      "import options",
      "importoptions",
      "add footage",
      "import png",
      "import video",
      "import mp4"
    ],
    "script": "app.beginUndoGroup(\"Import File\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  // Replace this path with the actual file path using forward slashes.\n  var filePath = \"/path/to/your/file.mp4\";\n  var file = new File(filePath);\n  if (!file.exists) {\n    throw new Error(\"File not found: \" + filePath);\n  }\n  var importOptions = new ImportOptions(file);\n  // Use ImportAsType.COMP for layered files (PSD, AI) to preserve layers.\n  // Use ImportAsType.FOOTAGE (the default) for video, image, and audio files.\n  importOptions.importAs = ImportAsType.FOOTAGE;\n  var footageItem = app.project.importFile(importOptions);\n  // Optionally add the imported footage to the active comp as a new layer.\n  var newLayer = comp.layers.add(footageItem);\n  newLayer.startTime = 0;\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "import",
      "file",
      "project",
      "footage",
      "importfile",
      "options",
      "importoptions",
      "png",
      "video",
      "mp4"
    ],
    "verifiedStatus": "verified",
    "notes": "Always use forward slashes in file paths (or a File object, which normalises them). Pick ImportAsType.COMP vs FOOTAGE deliberately for layered files like PSDs — COMP preserves layers, FOOTAGE flattens them."
  },
  {
    "id": "replace-footage-source",
    "description": "Replace footage source on a specific layer, or swap the project-panel item's source file",
    "keywords": [
      "replace footage",
      "replacesource",
      "swap footage",
      "change source",
      "replace file",
      "update footage",
      "relink footage"
    ],
    "script": "app.beginUndoGroup(\"Replace Footage\");\ntry {\n  var comp = app.project.activeItem;\n  if (!comp || !(comp instanceof CompItem)) {\n    throw new Error(\"Please select a composition.\");\n  }\n  if (comp.selectedLayers.length === 0) {\n    throw new Error(\"Select a layer to replace its source.\");\n  }\n  var layer = comp.selectedLayers[0];\n\n  // Option A: replaceSource -- changes which project item THIS layer references.\n  // Other layers using the original item are unaffected.\n  var newItem = app.project.importFile(\n    new ImportOptions(new File(\"/path/to/new-file.mov\"))\n  );\n  layer.replaceSource(newItem, false); // false = don't shift keyframes\n\n  // Option B: FootageItem.replace() -- changes the source FILE for the project item.\n  // ALL layers referencing that footage item update automatically.\n  // layer.source.replace(new File(\"/path/to/new-file.mov\"));\n} catch (e) {\n  alert(\"Error: \" + e.toString());\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "replace",
      "footage",
      "source",
      "specific",
      "swap",
      "project",
      "panel",
      "item",
      "file",
      "replacesource",
      "change",
      "update",
      "relink"
    ],
    "verifiedStatus": "verified",
    "notes": "Two distinct operations: replaceSource(newProjectItem, fixedToLayerTime) changes which project-panel item a specific layer references — other layers are unaffected. FootageItem.replace(file) changes the source file for the project item itself — all layers using that item update. The fixedToLayerTime boolean in replaceSource controls whether keyframes shift to maintain sync."
  },
  {
    "id": "add-mask-set-shape",
    "description": "Add mask to a layer and set its shape vertices, mode, and feather",
    "keywords": [
      "add mask",
      "mask shape",
      "mask vertices",
      "maskmode",
      "mask feather",
      "create mask",
      "mask path",
      "masking layer"
    ],
    "script": "app.beginUndoGroup(\"Add Mask\");\ntry {\n  var comp = app.project.activeItem;\n  if (!comp || !(comp instanceof CompItem)) {\n    throw new Error(\"Please select a composition.\");\n  }\n  if (comp.selectedLayers.length === 0) {\n    throw new Error(\"Select at least one layer.\");\n  }\n  var layer = comp.selectedLayers[0];\n  var newMask = layer.Masks.addProperty(\"Mask\");\n  newMask.maskMode = MaskMode.ADD;\n  newMask.inverted = false;\n  var maskPath = newMask.property(\"maskShape\");\n  var s = maskPath.value;\n  // Vertices are in layer space (centered at anchor point), not comp space.\n  s.vertices = [[0, 0], [200, 0], [200, 200], [0, 200]];\n  s.inTangents = [[0, 0], [0, 0], [0, 0], [0, 0]];\n  s.outTangents = [[0, 0], [0, 0], [0, 0], [0, 0]];\n  s.closed = true;\n  maskPath.setValue(s);\n  // Set feather (in pixels)\n  newMask.property(\"ADBE Mask Feather\").setValue(0);\n  // Optional: set mask opacity and expansion\n  // newMask.property(\"ADBE Mask Opacity\").setValue(100);\n  // newMask.property(\"ADBE Mask Expansion\").setValue(0);\n} catch (e) {\n  alert(\"Error: \" + e.toString());\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "mask",
      "shape",
      "vertices",
      "mode",
      "feather",
      "maskmode",
      "create",
      "path",
      "masking"
    ],
    "verifiedStatus": "verified",
    "notes": "MaskMode values: NONE, ADD, SUBTRACT, INTERSECT, LIGHTEN, DARKEN, DIFFERENCE. Vertices are in layer space (centered at the layer's anchor point), not comp space — this differs from shape layer vertices. maskPath.value always returns a Shape() object. All three arrays (vertices, inTangents, outTangents) must have the same length for Bezier paths."
  },
  {
    "id": "repeater-radial-burst",
    "description": "Build a radial burst from a shape rectangle and a Repeater with evenly distributed copies.",
    "keywords": [
      "radial burst",
      "shape repeater",
      "repeater copies",
      "sunburst"
    ],
    "script": "app.beginUndoGroup(\"Repeater Radial Burst\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) throw new Error(\"Open a composition.\");\n  var shape = comp.layers.addShape();\n  shape.name = \"Radial Burst\";\n  var contents = shape.property(\"ADBE Root Vectors Group\");\n  var group = contents.addProperty(\"ADBE Vector Group\");\n  var groupContents = group.property(\"ADBE Vectors Group\");\n  var rect = groupContents.addProperty(\"ADBE Vector Shape - Rect\");\n  rect.property(\"ADBE Vector Rect Size\").setValue([12, 180]);\n  rect.property(\"ADBE Vector Rect Position\").setValue([0, -150]);\n  var fill = groupContents.addProperty(\"ADBE Vector Graphic - Fill\");\n  fill.property(\"ADBE Vector Fill Color\").setValue([1, 0.3, 0.05, 1]);\n  var repeater = groupContents.addProperty(\"ADBE Vector Filter - Repeater\");\n  repeater.property(\"ADBE Vector Repeater Copies\").setValue(24);\n  repeater.property(\"ADBE Vector Repeater Transform\").property(\"ADBE Vector Repeater Rotation\").setValue(15);\n  shape.property(\"ADBE Transform Group\").property(\"ADBE Position\").setValue([comp.width / 2, comp.height / 2]);\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "build",
      "radial",
      "burst",
      "shape",
      "rectangle",
      "repeater",
      "evenly",
      "distributed",
      "copies",
      "sunburst"
    ],
    "verifiedStatus": "verified",
    "notes": "Uses verified shape-layer matchNames and RGBA fill values."
  },
  {
    "id": "shape-rect-stroke-fill",
    "description": "Add a rectangle with stroke and fill to a new shape layer",
    "keywords": [
      "shape layer",
      "rectangle",
      "rect",
      "stroke",
      "fill",
      "shape stroke",
      "shape fill",
      "vector group",
      "add shape"
    ],
    "script": "app.beginUndoGroup(\"Add Rectangle with Stroke and Fill\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  var layer = comp.layers.addShape();\n  layer.name = \"Rectangle\";\n  // All shape content lives under ADBE Root Vectors Group (the layer's Contents).\n  var contents = layer.property(\"ADBE Root Vectors Group\");\n  // Add a Group -- path, stroke, and fill are siblings inside the group's ADBE Vectors Group.\n  var group = contents.addProperty(\"ADBE Vector Group\");\n  group.name = \"Rect Group\";\n  var groupContents = group.property(\"ADBE Vectors Group\");\n  // Add the rect path inside the group.\n  var rect = groupContents.addProperty(\"ADBE Vector Shape - Rect\");\n  rect.property(\"ADBE Vector Rect Size\").setValue([400, 200]);\n  rect.property(\"ADBE Vector Rect Position\").setValue([0, 0]);\n  // Add stroke inside the same group (sibling of rect, not at root Contents level).\n  var stroke = groupContents.addProperty(\"ADBE Vector Graphic - Stroke\");\n  stroke.property(\"ADBE Vector Stroke Color\").setValue([1, 1, 1, 1]);\n  stroke.property(\"ADBE Vector Stroke Width\").setValue(4);\n  // Add fill inside the same group.\n  var fill = groupContents.addProperty(\"ADBE Vector Graphic - Fill\");\n  fill.property(\"ADBE Vector Fill Color\").setValue([0.2, 0.4, 0.8, 1]);\n  // Center the layer.\n  layer.property(\"ADBE Transform Group\").property(\"ADBE Position\").setValue([comp.width / 2, comp.height / 2]);\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "rectangle",
      "stroke",
      "fill",
      "shape",
      "rect",
      "vector",
      "group"
    ],
    "verifiedStatus": "verified",
    "notes": "Stroke and Fill must be siblings of the path shape inside the group's ADBE Vectors Group — adding them at the root Contents level (outside a group) causes them to appear at the wrong hierarchy level and affects all paths in the layer."
  },
  {
    "id": "trim-paths-animation",
    "description": "Animate Trim Paths Start and End on a shape layer",
    "keywords": [
      "trim paths",
      "trim path",
      "trim",
      "shape layer animation",
      "shape path",
      "vector trim",
      "start end"
    ],
    "script": "app.beginUndoGroup(\"Animate Trim Paths\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  var layer = comp.layers.addShape();\n  layer.name = \"Trim Paths Line\";\n  var contents = layer.property(\"ADBE Root Vectors Group\");\n  var group = contents.addProperty(\"ADBE Vector Group\");\n  group.name = \"Animated Line\";\n  var groupContents = group.property(\"ADBE Vectors Group\");\n  var rect = groupContents.addProperty(\"ADBE Vector Shape - Rect\");\n  rect.property(\"ADBE Vector Rect Size\").setValue([600, 180]);\n  rect.property(\"ADBE Vector Rect Position\").setValue([0, 0]);\n  var stroke = groupContents.addProperty(\"ADBE Vector Graphic - Stroke\");\n  stroke.property(\"ADBE Vector Stroke Color\").setValue([0.1, 0.8, 1, 1]);\n  stroke.property(\"ADBE Vector Stroke Width\").setValue(12);\n  var trim = groupContents.addProperty(\"ADBE Vector Filter - Trim\");\n  var startProp = trim.property(\"ADBE Vector Trim Start\");\n  var endProp = trim.property(\"ADBE Vector Trim End\");\n  startProp.setValueAtTime(0, 0);\n  startProp.setValueAtTime(2, 0);\n  endProp.setValueAtTime(0, 0);\n  endProp.setValueAtTime(2, 100);\n  layer.property(\"ADBE Transform Group\").property(\"ADBE Position\").setValue([comp.width / 2, comp.height / 2]);\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "animate",
      "trim",
      "paths",
      "start",
      "end",
      "shape",
      "path",
      "animation",
      "vector"
    ],
    "verifiedStatus": "verified",
    "notes": "Add shape operators to ADBE Vectors Group, then keyframe ADBE Vector Trim Start and ADBE Vector Trim End on the Trim Paths operator."
  },
  {
    "id": "per-character-3d-fade",
    "description": "Add a per-character 3D text animator that fades and moves characters into place.",
    "keywords": [
      "per character 3d",
      "character fade",
      "text animator 3d",
      "text cascade"
    ],
    "script": "app.beginUndoGroup(\"Per Character 3D Fade\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem) || comp.selectedLayers.length < 1 || !(comp.selectedLayers[0] instanceof TextLayer)) throw new Error(\"Select a text layer.\");\n  var layer = comp.selectedLayers[0];\n  layer.threeDPerChar = true;\n  var animator = layer.property(\"ADBE Text Properties\").property(\"ADBE Text Animators\").addProperty(\"ADBE Text Animator\");\n  animator.name = \"3D Fade\";\n  var props = animator.property(\"ADBE Text Animator Properties\");\n  props.addProperty(\"ADBE Text Opacity\").setValue(0);\n  props.addProperty(\"ADBE Text Position 3D\").setValue([0, 0, -100]);\n  var selector = animator.property(\"ADBE Text Selectors\").addProperty(\"ADBE Text Selector\");\n  var offset = selector.property(\"ADBE Text Percent Offset\");\n  offset.setValueAtTime(comp.time, -100);\n  offset.setValueAtTime(comp.time + 1.5, 100);\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "character",
      "text",
      "animator",
      "fades",
      "moves",
      "characters",
      "place",
      "fade",
      "cascade"
    ],
    "verifiedStatus": "verified",
    "notes": "Uses verified text animator property matchNames."
  },
  {
    "id": "text-box-sourcerect",
    "description": "Create a shape-layer text box that follows the selected text layer bounds with sourceRectAtTime expressions.",
    "keywords": [
      "text box",
      "sourcerect",
      "responsive box",
      "text background"
    ],
    "script": "app.beginUndoGroup(\"Responsive Text Box\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem) || comp.selectedLayers.length < 1 || !(comp.selectedLayers[0] instanceof TextLayer)) throw new Error(\"Select a text layer.\");\n  var textLayer = comp.selectedLayers[0];\n  var box = comp.layers.addShape();\n  box.name = textLayer.name + \" Box\";\n  var contents = box.property(\"ADBE Root Vectors Group\");\n  var group = contents.addProperty(\"ADBE Vector Group\");\n  var groupContents = group.property(\"ADBE Vectors Group\");\n  groupContents.addProperty(\"ADBE Vector Shape - Rect\");\n  groupContents.addProperty(\"ADBE Vector Graphic - Fill\");\n  var rect = groupContents.property(\"ADBE Vector Shape - Rect\");\n  var fill = groupContents.property(\"ADBE Vector Graphic - Fill\");\n  fill.property(\"ADBE Vector Fill Color\").setValue([0.1, 0.1, 0.1, 1]);\n  function quoteLayerName(value) {\n    var result = \"\";\n    for (var i = 0; i < value.length; i++) {\n      var ch = value.charAt(i);\n      if (ch === \"\\\\\" || ch === \"'\") result += \"\\\\\";\n      result += ch;\n    }\n    return result;\n  }\n  var escaped = quoteLayerName(textLayer.name);\n  rect.property(\"ADBE Vector Rect Size\").expression = \"var r = thisComp.layer('\" + escaped + \"').sourceRectAtTime(time, false);\\n[r.width + 40, r.height + 30];\";\n  rect.property(\"ADBE Vector Rect Position\").expression = \"var r = thisComp.layer('\" + escaped + \"').sourceRectAtTime(time, false);\\n[r.left + r.width / 2, r.top + r.height / 2];\";\n  box.property(\"ADBE Transform Group\").property(\"ADBE Position\").setValue(textLayer.property(\"ADBE Transform Group\").property(\"ADBE Position\").value);\n  box.moveAfter(textLayer);\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "create",
      "shape",
      "text",
      "box",
      "follows",
      "bounds",
      "sourcerectattime",
      "expressions",
      "sourcerect",
      "responsive",
      "background"
    ],
    "verifiedStatus": "verified",
    "notes": "Calls sourceRectAtTime() once per expression evaluation."
  },
  {
    "id": "text-color-keyframe",
    "description": "Animate text fill color by keyframing Source Text with different TextDocument values",
    "keywords": [
      "text color",
      "animate text color",
      "text fill color",
      "fillcolor",
      "text keyframe",
      "source text keyframe",
      "color animation",
      "text animation"
    ],
    "script": "app.beginUndoGroup(\"Animate Text Color\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  if (comp.selectedLayers.length < 1) {\n    throw new Error(\"Select a text layer.\");\n  }\n  var layer = comp.selectedLayers[0];\n  var textProp = layer.property(\"ADBE Text Properties\").property(\"ADBE Text Document\");\n  // Read the current TextDocument to preserve font, size, and content.\n  var docStart = textProp.value;\n  docStart.applyFill = true;\n  // fillColor uses 0.0-1.0 float components, NOT 0-255.\n  docStart.fillColor = [1, 0, 0];\n  textProp.setValueAtTime(0, docStart);\n  // Create a second TextDocument for the end color.\n  // In-place mutation of the same object does NOT create a new keyframe --\n  // you must pass a distinct TextDocument to each setValueAtTime call.\n  var docEnd = textProp.value;\n  docEnd.applyFill = true;\n  docEnd.fillColor = [0, 0, 1];\n  textProp.setValueAtTime(2, docEnd);\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "animate",
      "text",
      "fill",
      "color",
      "keyframing",
      "source",
      "different",
      "textdocument",
      "values",
      "fillcolor",
      "keyframe",
      "animation"
    ],
    "verifiedStatus": "verified",
    "notes": "fillColor uses 0.0-1.0 floats (not 0-255). You must call setValueAtTime with a TextDocument object each time — setting a property on the existing doc and calling setValue() again does NOT create a new keyframe, it replaces the last one."
  },
  {
    "id": "text-layer-creation",
    "description": "Create a text layer and set font, size, fill color, and justification",
    "keywords": [
      "text layer",
      "addtext",
      "textdocument",
      "source text",
      "font",
      "font size",
      "fontsize",
      "fill color",
      "justification"
    ],
    "script": "app.beginUndoGroup(\"Create Text Layer\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  var textLayer = comp.layers.addText(\"Welcome\");\n  var textProp = textLayer.property(\"ADBE Text Properties\").property(\"ADBE Text Document\");\n  var textDoc = textProp.value;\n  textDoc.font = \"ArialMT\";\n  textDoc.fontSize = 48;\n  textDoc.applyFill = true;\n  textDoc.fillColor = [1, 1, 1];\n  textDoc.justification = ParagraphJustification.CENTER_JUSTIFY;\n  textProp.setValue(textDoc);\n  textLayer.property(\"ADBE Transform Group\").property(\"ADBE Anchor Point\").setValue([0, 0]);\n  textLayer.property(\"ADBE Transform Group\").property(\"ADBE Position\").setValue([comp.width / 2, comp.height / 2]);\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "create",
      "text",
      "font",
      "size",
      "fill",
      "color",
      "justification",
      "addtext",
      "textdocument",
      "source",
      "fontsize"
    ],
    "verifiedStatus": "verified",
    "notes": "Read TextDocument with .value, mutate the local object, then write it back with .setValue(). Set applyFill before fillColor."
  },
  {
    "id": "typewriter-text-animator",
    "description": "Create a typewriter reveal on the selected text layer with a Text Animator range selector.",
    "keywords": [
      "typewriter",
      "text reveal",
      "typing animation",
      "range selector"
    ],
    "script": "app.beginUndoGroup(\"Typewriter Text Animator\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem) || comp.selectedLayers.length < 1 || !(comp.selectedLayers[0] instanceof TextLayer)) throw new Error(\"Select a text layer.\");\n  var layer = comp.selectedLayers[0];\n  var animators = layer.property(\"ADBE Text Properties\").property(\"ADBE Text Animators\");\n  var animator = animators.addProperty(\"ADBE Text Animator\");\n  animator.name = \"Typewriter\";\n  animator.property(\"ADBE Text Animator Properties\").addProperty(\"ADBE Text Opacity\").setValue(0);\n  var selector = animator.property(\"ADBE Text Selectors\").addProperty(\"ADBE Text Selector\");\n  var end = selector.property(\"ADBE Text Percent End\");\n  end.setValueAtTime(comp.time, 0);\n  end.setValueAtTime(comp.time + 2, 100);\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "create",
      "typewriter",
      "reveal",
      "text",
      "animator",
      "range",
      "selector",
      "typing",
      "animation"
    ],
    "verifiedStatus": "verified",
    "notes": "Uses verified text-layer matchNames."
  },
  {
    "id": "add-layer-marker",
    "description": "Add marker with a comment to a layer or composition at a specific time",
    "keywords": [
      "add marker",
      "layer marker",
      "comp marker",
      "composition marker",
      "markervalue",
      "marker comment",
      "set marker"
    ],
    "script": "app.beginUndoGroup(\"Add Marker\");\ntry {\n  var comp = app.project.activeItem;\n  if (!comp || !(comp instanceof CompItem)) {\n    throw new Error(\"Please select a composition.\");\n  }\n  // --- Layer marker ---\n  if (comp.selectedLayers.length > 0) {\n    var layer = comp.selectedLayers[0];\n    var mv = new MarkerValue(\"My Marker\");\n    mv.duration = 0; // 0 = point marker; set > 0 for a duration span\n    layer.property(\"Marker\").setValueAtTime(1.0, mv); // 1.0 = time in seconds\n  }\n  // --- Composition marker ---\n  // var compMv = new MarkerValue(\"Comp Marker\");\n  // comp.markerProperty.setValueAtTime(2.0, compMv);\n} catch (e) {\n  alert(\"Error: \" + e.toString());\n} finally {\n  app.endUndoGroup();\n}\n\n// Read a marker's comment:\n// var comment = layer.property(\"Marker\").keyValue(1).comment;",
    "terms": [
      "marker",
      "comment",
      "composition",
      "specific",
      "time",
      "comp",
      "markervalue"
    ],
    "verifiedStatus": "verified",
    "notes": "MarkerValue constructor takes a comment string. Set mv.duration for a span marker (in seconds). Composition markers use comp.markerProperty.setValueAtTime() — this was unsupported before AE CC 2014 but is now standard. To read a marker: layer.property('Marker').keyValue(1).comment retrieves the first marker's comment."
  },
  {
    "id": "expression-error-scan",
    "description": "Scan every expression-enabled property in the active comp and report expressionError messages with layer and property names.",
    "keywords": [
      "expression error scan",
      "find broken expressions",
      "expressionerror",
      "troubleshoot expressions"
    ],
    "script": "app.beginUndoGroup(\"Expression Error Scan\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) throw new Error(\"Open a composition.\");\n  var errors = [];\n  function walk(group, layerName) {\n    for (var i = 1; i <= group.numProperties; i++) {\n      var item = group.property(i);\n      if (!item) continue;\n      if (item instanceof Property) {\n        if (item.canSetExpression && item.expressionEnabled) {\n          try { item.valueAtTime(comp.time, false); } catch (e) {}\n          if (item.expressionError) errors.push(layerName + \" > \" + item.name + \": \" + item.expressionError);\n        }\n      } else {\n        walk(item, layerName);\n      }\n    }\n  }\n  for (var layerIndex = 1; layerIndex <= comp.numLayers; layerIndex++) walk(comp.layer(layerIndex), comp.layer(layerIndex).name);\n  if (errors.length) alert(errors.join(\"\\n\\n\"));\n  else alert(\"No expression errors found.\");\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "scan",
      "every",
      "expression",
      "enabled",
      "property",
      "active",
      "comp",
      "report",
      "expressionerror",
      "messages",
      "names",
      "error",
      "find",
      "broken",
      "expressions",
      "troubleshoot"
    ],
    "verifiedStatus": "pending",
    "notes": "AE runtime verification pending. Forces valueAtTime() before reading expressionError."
  },
  {
    "id": "instanceof-comp-guard",
    "description": "Active item guard before accessing layers or properties",
    "keywords": [
      "instanceof compitem",
      "active item guard",
      "comp guard",
      "check active comp",
      "no composition selected",
      "null check project",
      "safe comp access"
    ],
    "script": "app.beginUndoGroup(\"Script Name\");\ntry {\n  if (!app.project) {\n    throw new Error(\"No project is open.\");\n  }\n  var comp = app.project.activeItem;\n  if (!comp || !(comp instanceof CompItem)) {\n    throw new Error(\"Please select a composition in the Project panel.\");\n  }\n  // Safe to access comp.numLayers, comp.layers, comp.selectedLayers, etc.\n  var numLayers = comp.numLayers;\n  // ... your script logic here ...\n} catch (e) {\n  alert(\"Error: \" + e.toString());\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "active",
      "item",
      "guard",
      "before",
      "accessing",
      "properties",
      "instanceof",
      "compitem",
      "comp",
      "check",
      "composition",
      "null",
      "project",
      "safe",
      "access"
    ],
    "verifiedStatus": "verified",
    "notes": "app.project.activeItem can be null (no project), a FootageItem, a FolderItem, or a CompItem. Accessing .numLayers or .layers on a null or non-comp item throws immediately. Always check app.project first, then instanceof CompItem. The .typeName string ('Footage', 'Composition', 'Folder') is an alternative filter but instanceof is preferred."
  },
  {
    "id": "recursive-property-walk",
    "description": "Recursively walk all properties of a layer and operate on leaf properties by matchName",
    "keywords": [
      "recursive property",
      "walk properties",
      "loop properties",
      "iterate properties",
      "property tree",
      "matchname",
      "numproperties",
      "property group"
    ],
    "script": "app.beginUndoGroup(\"Walk Properties\");\ntry {\n  var comp = app.project.activeItem;\n  if (!comp || !(comp instanceof CompItem)) {\n    throw new Error(\"Please select a composition.\");\n  }\n  if (comp.selectedLayers.length === 0) {\n    throw new Error(\"Select a layer.\");\n  }\n  var layer = comp.selectedLayers[0];\n  walkProperties(layer, function(prop) {\n    // Example: log every property's matchName and current value\n    if (prop.numProperties === 0) {\n      // Leaf property -- safe to read .value\n      // $.writeln(prop.matchName + \": \" + prop.value);\n    }\n  });\n} catch (e) {\n  alert(\"Error: \" + e.toString());\n} finally {\n  app.endUndoGroup();\n}\n\nfunction walkProperties(propertyGroup, callback) {\n  var i;\n  for (i = 1; i <= propertyGroup.numProperties; i++) {\n    var prop = propertyGroup.property(i);\n    callback(prop);\n    if (prop.numProperties > 0) {\n      walkProperties(prop, callback);\n    }\n  }\n}",
    "terms": [
      "recursively",
      "walk",
      "properties",
      "operate",
      "leaf",
      "matchname",
      "recursive",
      "property",
      "loop",
      "iterate",
      "tree",
      "numproperties",
      "group"
    ],
    "verifiedStatus": "verified",
    "notes": "Use prop.matchName for stable property identification — it is locale-independent and survives layer renames. prop.name is locale-dependent and user-editable. PropertyType.INDEXED_GROUP and NAMED_GROUP have numProperties > 0; leaf properties have numProperties === 0. Reading .value on a group throws — always guard with numProperties check."
  },
  {
    "id": "undo-group-try-finally",
    "description": "Wrap all mutations in beginUndoGroup/endUndoGroup with try/catch/finally for safe error handling",
    "keywords": [
      "undo group",
      "beginundogroup",
      "endundogroup",
      "try catch finally",
      "error handling",
      "undo wrap",
      "safe script boilerplate"
    ],
    "script": "app.beginUndoGroup(\"My Script Name\");\ntry {\n  var comp = app.project.activeItem;\n  if (!comp || !(comp instanceof CompItem)) {\n    throw new Error(\"Please select a composition.\");\n  }\n  // All mutations go here.\n  // Thrown errors will skip to catch, endUndoGroup still runs via finally.\n} catch (e) {\n  alert(\"Error: \" + e.toString());\n} finally {\n  app.endUndoGroup();\n}",
    "terms": [
      "wrap",
      "mutations",
      "beginundogroup",
      "endundogroup",
      "try",
      "catch",
      "finally",
      "safe",
      "error",
      "handling",
      "undo",
      "group",
      "script",
      "boilerplate"
    ],
    "verifiedStatus": "verified",
    "notes": "Critical: in AE 2023+, calling app.beginUndoGroup() during ScriptUI panel initialization (on script load) throws 'Unknown Exception'. Defer all beginUndoGroup calls to user-triggered events (button clicks). Also: calling app.executeCommand() inside an open undo group silently opens a nested group, causing 'Undo group mismatch' warnings in AE 2023. Keep undo groups flat."
  }
];
