// AUTO-GENERATED by scripts/generate-knowledge.mjs — do not edit manually
// Source: /Users/randycounsman/Git/ae-ai-chat/recipes (13 recipes)

export interface RecipeEntry {
  id: string;
  description: string;
  keywords: string[];
  script: string;
  notes?: string;
}

export const RECIPES: RecipeEntry[] = [
  {
    "id": "copy-keyframes",
    "description": "Copy all keyframes from one property to another",
    "keywords": [
      "copy keyframes",
      "copy keys",
      "keyframe copy",
      "transfer keyframes",
      "paste keyframes",
      "duplicate keyframes"
    ],
    "script": "app.beginUndoGroup(\"Copy Keyframes\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  if (comp.selectedLayers.length < 1) {\n    throw new Error(\"Select at least one layer.\");\n  }\n  var layer = comp.selectedLayers[0];\n  var srcProp = layer.property(\"ADBE Transform Group\").property(\"ADBE Opacity\");\n  var dstProp = layer.property(\"ADBE Transform Group\").property(\"ADBE Opacity\");\n  // Replace srcProp and dstProp with the actual source and destination properties.\n  // Both properties must exist on accessible layers in the composition.\n  var keyCount = srcProp.numKeys;\n  if (keyCount === 0) {\n    throw new Error(\"Source property has no keyframes.\");\n  }\n  // Snapshot all keyframe data before modifying anything.\n  var snapTimes = [];\n  var snapValues = [];\n  var snapInEase = [];\n  var snapOutEase = [];\n  var i;\n  for (i = 1; i <= keyCount; i++) {\n    snapTimes.push(srcProp.keyTime(i));\n    snapValues.push(srcProp.keyValue(i));\n    snapInEase.push(srcProp.keyInTemporalEase(i));\n    snapOutEase.push(srcProp.keyOutTemporalEase(i));\n  }\n  // Write keyframes to destination, then apply ease.\n  for (i = 0; i < keyCount; i++) {\n    dstProp.setValueAtTime(snapTimes[i], snapValues[i]);\n  }\n  for (i = 0; i < keyCount; i++) {\n    dstProp.setTemporalEaseAtKey(i + 1, snapInEase[i], snapOutEase[i]);\n  }\n} finally {\n  app.endUndoGroup();\n}",
    "notes": "There is no native copyKeyframes() API. Always snapshot all keyframe data into arrays first, then write setValueAtTime, then re-apply ease — setting ease changes key indices, so re-apply in a second pass. Spatial properties also need setSpatialTangentsAtKey after the ease pass."
  },
  {
    "id": "duplicate-layer-offset",
    "description": "Duplicate a layer and offset the copy in comp time",
    "keywords": [
      "duplicate layer",
      "duplicate",
      "layer offset",
      "offset in time",
      "stagger",
      "starttime",
      "layer copy"
    ],
    "script": "app.beginUndoGroup(\"Duplicate and Offset Layer\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  if (comp.selectedLayers.length < 1) {\n    throw new Error(\"Select a layer to duplicate.\");\n  }\n  var original = comp.selectedLayers[0];\n  // duplicate() inserts the copy at index 1 (top of stack).\n  var copy = original.duplicate();\n  copy.name = original.name + \" copy\";\n  // startTime slides the whole layer bar in comp time (not a trim handle).\n  // .inPoint and .outPoint are trim positions — distinct from startTime.\n  var offsetSeconds = 0.5;\n  copy.startTime = original.startTime + offsetSeconds;\n} finally {\n  app.endUndoGroup();\n}",
    "notes": "duplicate() always inserts the new layer at index 1. Use .startTime to slide the layer bar in comp time; do NOT confuse with .inPoint/.outPoint which are trim handles on the source."
  },
  {
    "id": "effect-manipulation",
    "description": "Add an effect, set multiple properties, and animate an effect property",
    "keywords": [
      "effect manipulation",
      "effect properties",
      "animate effect",
      "setvalueattime",
      "addproperty",
      "multiple properties"
    ],
    "script": "app.beginUndoGroup(\"Animate Effect Properties\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  var layer;\n  if (comp.selectedLayers.length > 0) {\n    layer = comp.selectedLayers[0];\n  } else {\n    layer = comp.layers.addSolid([0.2, 0.2, 0.2], \"Effect Target\", comp.width, comp.height, comp.pixelAspect, comp.duration);\n  }\n  var effects = layer.property(\"ADBE Effect Parade\");\n  var blur = effects.addProperty(\"ADBE Gaussian Blur 2\");\n  var blurriness = blur.property(\"ADBE Gaussian Blur 2-0001\");\n  blurriness.setValueAtTime(0, 0);\n  blurriness.setValueAtTime(1, 40);\n  blur.property(\"ADBE Gaussian Blur 2-0002\").setValue(1);\n  blur.property(\"ADBE Gaussian Blur 2-0003\").setValue(1);\n} finally {\n  app.endUndoGroup();\n}",
    "notes": "Use addProperty with the verified effect matchName, then access individual effect properties by verified property matchName."
  },
  {
    "id": "expression-on-property",
    "description": "Set an initial property value, then assign an expression string",
    "keywords": [
      "expression",
      "expressions",
      "property expression",
      "expression string",
      "expression engine",
      "wiggle"
    ],
    "script": "app.beginUndoGroup(\"Assign Expression\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  var layer = comp.layers.addSolid([0.15, 0.18, 0.24], \"Expression Opacity\", comp.width, comp.height, comp.pixelAspect, comp.duration);\n  var opacity = layer.property(\"ADBE Transform Group\").property(\"ADBE Opacity\");\n  opacity.setValue(80);\n  opacity.expression = \"var base = 80;\\nvar amount = 20;\\nbase + Math.sin(time * 6) * amount;\";\n  if (opacity.expressionError !== \"\") {\n    throw new Error(opacity.expressionError);\n  }\n} finally {\n  app.endUndoGroup();\n}",
    "notes": "Use setValue or setValueAtTime for script-side values. Assign expressions as strings to .expression, then check expressionError."
  },
  {
    "id": "import-file",
    "description": "Import a file into the project as Footage",
    "keywords": [
      "import file",
      "importfile",
      "import footage",
      "import options",
      "importoptions",
      "add footage",
      "import png",
      "import video",
      "import mp4"
    ],
    "script": "app.beginUndoGroup(\"Import File\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  // Replace this path with the actual file path using forward slashes.\n  var filePath = \"/path/to/your/file.mp4\";\n  var file = new File(filePath);\n  if (!file.exists) {\n    throw new Error(\"File not found: \" + filePath);\n  }\n  var importOptions = new ImportOptions(file);\n  // Use ImportAsType.COMP for layered files (PSD, AI) to preserve layers.\n  // Use ImportAsType.FOOTAGE (the default) for video, image, and audio files.\n  importOptions.importAs = ImportAsType.FOOTAGE;\n  var footageItem = app.project.importFile(importOptions);\n  // Optionally add the imported footage to the active comp as a new layer.\n  var newLayer = comp.layers.add(footageItem);\n  newLayer.startTime = 0;\n} finally {\n  app.endUndoGroup();\n}",
    "notes": "Always use forward slashes in file paths (or a File object, which normalises them). Pick ImportAsType.COMP vs FOOTAGE deliberately for layered files like PSDs — COMP preserves layers, FOOTAGE flattens them."
  },
  {
    "id": "keyframe-temporal-ease",
    "description": "Create keyframes and apply KeyframeEase with setTemporalEaseAtKey",
    "keywords": [
      "keyframe ease",
      "keyframeease",
      "temporal ease",
      "settemporaleaseatkey",
      "easing",
      "ease keyframes",
      "eased keyframes"
    ],
    "script": "app.beginUndoGroup(\"Ease Opacity Keyframes\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  var layer = comp.layers.addSolid([1, 0.45, 0.1], \"Eased Opacity\", comp.width, comp.height, comp.pixelAspect, comp.duration);\n  var opacity = layer.property(\"ADBE Transform Group\").property(\"ADBE Opacity\");\n  opacity.setValueAtTime(0, 0);\n  opacity.setValueAtTime(1, 100);\n  var easeIn = new KeyframeEase(0, 80);\n  var easeOut = new KeyframeEase(0, 80);\n  opacity.setTemporalEaseAtKey(1, [easeIn], [easeOut]);\n  opacity.setTemporalEaseAtKey(2, [easeIn], [easeOut]);\n} finally {\n  app.endUndoGroup();\n}",
    "notes": "setTemporalEaseAtKey takes arrays of KeyframeEase objects. One-dimensional properties use one ease object per side."
  },
  {
    "id": "parent-layer-by-name",
    "description": "Parent one layer to another by name without a transform jump",
    "keywords": [
      "parent layer",
      "parent",
      "parenting",
      "layer parent",
      "setparentwithjump",
      "parent by name",
      "null parent"
    ],
    "script": "app.beginUndoGroup(\"Parent Layer by Name\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  var childName = \"Title\";\n  var parentName = \"Background Box\";\n  var child = comp.layer(childName);\n  if (!child) {\n    throw new Error(\"Layer not found: \" + childName);\n  }\n  var parent = comp.layer(parentName);\n  if (!parent) {\n    throw new Error(\"Layer not found: \" + parentName);\n  }\n  // Assigning .parent compensates transforms so the layer does not jump visually.\n  // Use setParentWithJump(parent) if you want to preserve the raw transform values\n  // and intentionally accept the visual snap (e.g. locking values before rigging).\n  child.parent = parent;\n} finally {\n  app.endUndoGroup();\n}",
    "notes": "layer.parent = target auto-calculates a transform offset to prevent a visual jump. setParentWithJump(target) preserves the raw values and snaps visually — pick deliberately based on whether you want the child to stay in place or keep its current numeric values."
  },
  {
    "id": "precompose-selected-layers",
    "description": "Pre-compose the currently selected layers into a new comp",
    "keywords": [
      "precompose",
      "pre-compose",
      "pre compose",
      "nest layers",
      "nest into comp",
      "group layers",
      "precomp"
    ],
    "script": "app.beginUndoGroup(\"Pre-compose Selected Layers\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  if (comp.selectedLayers.length === 0) {\n    throw new Error(\"Select at least one layer to pre-compose.\");\n  }\n  // Collect 1-based integer indices — precompose() does NOT accept Layer objects.\n  var indices = [];\n  var i;\n  for (i = 0; i < comp.selectedLayers.length; i++) {\n    indices.push(comp.selectedLayers[i].index);\n  }\n  // Sort ascending — precompose expects a sorted index array.\n  indices.sort(function(a, b) { return a - b; });\n  var newCompName = \"Precomp\";\n  // moveAllAttributes=true (the default) moves all layer attributes into the new comp.\n  // Set to false only when pre-composing a single layer and you want to keep attributes.\n  var newComp = comp.layers.precompose(indices, newCompName, true);\n} finally {\n  app.endUndoGroup();\n}",
    "notes": "precompose() takes an array of 1-based integer indices, NOT Layer objects. moveAllAttributes defaults to true; setting it to false is only valid when the array has exactly one index. Returns the new CompItem."
  },
  {
    "id": "shape-rect-stroke-fill",
    "description": "Add a rectangle with stroke and fill to a new shape layer",
    "keywords": [
      "shape layer",
      "rectangle",
      "rect",
      "stroke",
      "fill",
      "shape stroke",
      "shape fill",
      "vector group",
      "add shape"
    ],
    "script": "app.beginUndoGroup(\"Add Rectangle with Stroke and Fill\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  var layer = comp.layers.addShape();\n  layer.name = \"Rectangle\";\n  // All shape content lives under ADBE Root Vectors Group (the layer's Contents).\n  var contents = layer.property(\"ADBE Root Vectors Group\");\n  // Add a Group — path, stroke, and fill are siblings inside the group's ADBE Vectors Group.\n  var group = contents.addProperty(\"ADBE Vector Group\");\n  group.name = \"Rect Group\";\n  var groupContents = group.property(\"ADBE Vectors Group\");\n  // Add the rect path inside the group.\n  var rect = groupContents.addProperty(\"ADBE Vector Shape - Rect\");\n  rect.property(\"ADBE Vector Rect Size\").setValue([400, 200]);\n  rect.property(\"ADBE Vector Rect Position\").setValue([0, 0]);\n  // Add stroke inside the same group (sibling of rect, not at root Contents level).\n  var stroke = groupContents.addProperty(\"ADBE Vector Graphic - Stroke\");\n  stroke.property(\"ADBE Vector Stroke Color\").setValue([1, 1, 1, 1]);\n  stroke.property(\"ADBE Vector Stroke Width\").setValue(4);\n  // Add fill inside the same group.\n  var fill = groupContents.addProperty(\"ADBE Vector Graphic - Fill\");\n  fill.property(\"ADBE Vector Fill Color\").setValue([0.2, 0.4, 0.8, 1]);\n  // Center the layer.\n  layer.property(\"ADBE Transform Group\").property(\"ADBE Position\").setValue([comp.width / 2, comp.height / 2]);\n} finally {\n  app.endUndoGroup();\n}",
    "notes": "Stroke and Fill must be siblings of the path shape inside the group's ADBE Vectors Group — adding them at the root Contents level (outside a group) causes them to appear at the wrong hierarchy level and affects all paths in the layer."
  },
  {
    "id": "spatial-tangent-ease",
    "description": "Set spatial ease on Position keyframes for a curved motion path",
    "keywords": [
      "spatial ease",
      "spatial tangent",
      "curved path",
      "motion path",
      "bezier path",
      "position ease",
      "setspatialatkey",
      "setspatial"
    ],
    "script": "app.beginUndoGroup(\"Set Spatial Ease on Position\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  if (comp.selectedLayers.length < 1) {\n    throw new Error(\"Select a layer.\");\n  }\n  var layer = comp.selectedLayers[0];\n  var position = layer.property(\"ADBE Transform Group\").property(\"ADBE Position\");\n  // Create at least two position keyframes first.\n  var cx = comp.width / 2;\n  var cy = comp.height / 2;\n  position.setValueAtTime(0, [cx - 300, cy]);\n  position.setValueAtTime(1, [cx, cy - 200]);\n  position.setValueAtTime(2, [cx + 300, cy]);\n  // setSpatialTangentsAtKey only works on spatial (TwoD_SPATIAL / ThreeD_SPATIAL) properties.\n  // It does NOT work on Scale, Opacity, or other non-spatial properties.\n  // Disable auto-bezier and continuous bezier so AE does not override the tangents.\n  var keyIndex;\n  for (keyIndex = 1; keyIndex <= position.numKeys; keyIndex++) {\n    position.setSpatialAutoBezierAtKey(keyIndex, false);\n    position.setSpatialContinuousAtKey(keyIndex, false);\n    // inTangent and outTangent are [x, y] pixel offsets from the keyframe anchor.\n    position.setSpatialTangentsAtKey(keyIndex, [-100, 0], [100, 0]);\n  }\n} finally {\n  app.endUndoGroup();\n}",
    "notes": "setSpatialTangentsAtKey only works on TwoD_SPATIAL or ThreeD_SPATIAL properties (e.g. Position) — calling it on Scale or Opacity throws. Always call setSpatialAutoBezierAtKey(keyIndex, false) and setSpatialContinuousAtKey(keyIndex, false) first, otherwise AE overrides your tangents on the next frame render."
  },
  {
    "id": "text-color-keyframe",
    "description": "Animate text fill color by keyframing Source Text with different TextDocument values",
    "keywords": [
      "text color",
      "animate text color",
      "text fill color",
      "fillcolor",
      "text keyframe",
      "source text keyframe",
      "color animation",
      "text animation"
    ],
    "script": "app.beginUndoGroup(\"Animate Text Color\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  if (comp.selectedLayers.length < 1) {\n    throw new Error(\"Select a text layer.\");\n  }\n  var layer = comp.selectedLayers[0];\n  var textProp = layer.property(\"ADBE Text Properties\").property(\"ADBE Text Document\");\n  // Read the current TextDocument to preserve font, size, and content.\n  var docStart = textProp.value;\n  docStart.applyFill = true;\n  // fillColor uses 0.0-1.0 float components, NOT 0-255.\n  docStart.fillColor = [1, 0, 0];\n  textProp.setValueAtTime(0, docStart);\n  // Create a second TextDocument for the end color.\n  // In-place mutation of the same object does NOT create a new keyframe —\n  // you must pass a distinct TextDocument to each setValueAtTime call.\n  var docEnd = textProp.value;\n  docEnd.applyFill = true;\n  docEnd.fillColor = [0, 0, 1];\n  textProp.setValueAtTime(2, docEnd);\n} finally {\n  app.endUndoGroup();\n}",
    "notes": "fillColor uses 0.0-1.0 floats (not 0-255). You must call setValueAtTime with a TextDocument object each time — setting a property on the existing doc and calling setValue() again does NOT create a new keyframe, it replaces the last one."
  },
  {
    "id": "text-layer-creation",
    "description": "Create a text layer and set font, size, fill color, and justification",
    "keywords": [
      "text layer",
      "addtext",
      "textdocument",
      "source text",
      "font",
      "font size",
      "fontsize",
      "fill color",
      "justification"
    ],
    "script": "app.beginUndoGroup(\"Create Text Layer\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  var textLayer = comp.layers.addText(\"Welcome\");\n  var textProp = textLayer.property(\"ADBE Text Properties\").property(\"ADBE Text Document\");\n  var textDoc = textProp.value;\n  textDoc.font = \"ArialMT\";\n  textDoc.fontSize = 48;\n  textDoc.applyFill = true;\n  textDoc.fillColor = [1, 1, 1];\n  textDoc.justification = ParagraphJustification.CENTER_JUSTIFY;\n  textProp.setValue(textDoc);\n  textLayer.property(\"ADBE Transform Group\").property(\"ADBE Anchor Point\").setValue([0, 0]);\n  textLayer.property(\"ADBE Transform Group\").property(\"ADBE Position\").setValue([comp.width / 2, comp.height / 2]);\n} finally {\n  app.endUndoGroup();\n}",
    "notes": "Read TextDocument with .value, mutate the local object, then write it back with .setValue(). Set applyFill before fillColor."
  },
  {
    "id": "trim-paths-animation",
    "description": "Animate Trim Paths Start and End on a shape layer",
    "keywords": [
      "trim paths",
      "trim path",
      "trim",
      "shape layer animation",
      "shape path",
      "vector trim",
      "start end"
    ],
    "script": "app.beginUndoGroup(\"Animate Trim Paths\");\ntry {\n  var comp = app.project.activeItem;\n  if (!(comp instanceof CompItem)) {\n    throw new Error(\"Open a composition first.\");\n  }\n  var layer = comp.layers.addShape();\n  layer.name = \"Trim Paths Line\";\n  var contents = layer.property(\"ADBE Root Vectors Group\");\n  var group = contents.addProperty(\"ADBE Vector Group\");\n  group.name = \"Animated Line\";\n  var groupContents = group.property(\"ADBE Vectors Group\");\n  var rect = groupContents.addProperty(\"ADBE Vector Shape - Rect\");\n  rect.property(\"ADBE Vector Rect Size\").setValue([600, 180]);\n  rect.property(\"ADBE Vector Rect Position\").setValue([0, 0]);\n  var stroke = groupContents.addProperty(\"ADBE Vector Graphic - Stroke\");\n  stroke.property(\"ADBE Vector Stroke Color\").setValue([0.1, 0.8, 1, 1]);\n  stroke.property(\"ADBE Vector Stroke Width\").setValue(12);\n  var trim = groupContents.addProperty(\"ADBE Vector Filter - Trim\");\n  var startProp = trim.property(\"ADBE Vector Trim Start\");\n  var endProp = trim.property(\"ADBE Vector Trim End\");\n  startProp.setValueAtTime(0, 0);\n  startProp.setValueAtTime(2, 0);\n  endProp.setValueAtTime(0, 0);\n  endProp.setValueAtTime(2, 100);\n  layer.property(\"ADBE Transform Group\").property(\"ADBE Position\").setValue([comp.width / 2, comp.height / 2]);\n} finally {\n  app.endUndoGroup();\n}",
    "notes": "Add shape operators to ADBE Vectors Group, then keyframe ADBE Vector Trim Start and ADBE Vector Trim End on the Trim Paths operator."
  }
];

