import { fs, path, os, child_process } from "./cep/node";
import type { ScriptValidationResult } from "./knowledge/validator";
import { validateScript } from "./knowledge/validator";
import { csi, evalTS } from "./utils/bolt";
import { findGitRoot } from "./providers/shared";
import { prepareExpressionCapture } from "./expression-rewriter";

const ACTION_DIR = ".session";
const ACTION_FILE = "ai-action.jsx";
const META_FILE = "ai-action.json";

export interface AiActionState {
  scriptPath: string;
  metaPath: string;
  summary: string;
  updatedAt: string;
}

export interface ParsedAiActionResponse {
  displayText: string;
  scriptContent?: string;
  runImmediately: boolean;
  multipleBlocks?: boolean;
  validation?: ScriptValidationResult;
}

function resolveRepoRoot(projectRoot?: string): string | null {
  const repoRoot = findGitRoot(projectRoot);
  if (repoRoot) return repoRoot;
  if (projectRoot) return projectRoot;
  return null;
}

function resolveExampleRoot(projectRoot?: string): string | null {
  try {
    const extensionRoot = csi.getSystemPath("extension");
    if (extensionRoot) {
      return path.resolve(extensionRoot, "..", "..");
    }
  } catch {}

  const repoRoot = resolveRepoRoot(projectRoot);
  if (!repoRoot) return null;

  return path.join(repoRoot, "examples", "ai-chat");
}

function resolveAiActionPaths(projectRoot?: string) {
  const exampleRoot = resolveExampleRoot(projectRoot);
  if (!exampleRoot) return null;

  const actionDir = path.join(exampleRoot, ACTION_DIR);
  return {
    actionDir,
    scriptPath: path.join(actionDir, ACTION_FILE),
    metaPath: path.join(actionDir, META_FILE),
  };
}

function ensureActionDir(actionDir: string) {
  fs.mkdirSync(actionDir, { recursive: true });
}

function buildScriptHeader(summary: string): string {
  return [
    "// AI Action",
    "// Temporary session script generated by the AI chat panel.",
    "// This file is overwritten frequently and should not be committed.",
    "// Summary: " + summary,
    "",
  ].join("\n");
}

function uniquePaths(values: Array<string | null | undefined>): string[] {
  const seen: Record<string, true> = {};
  const result: string[] = [];

  for (const value of values) {
    if (!value) continue;
    const normalized = path.resolve(value);
    if (seen[normalized]) continue;
    seen[normalized] = true;
    result.push(normalized);
  }

  return result;
}

function buildIncludeSearchRoots(projectRoot?: string): string[] {
  const repoRoot = resolveRepoRoot(projectRoot);
  const extensionRoot = (() => {
    try {
      return csi.getSystemPath("extension");
    } catch {
      return "";
    }
  })();

  return uniquePaths([
    projectRoot,
    projectRoot ? path.join(projectRoot, "Scripts") : null,
    projectRoot ? path.join(projectRoot, "Scripts", "recipes") : null,
    repoRoot,
    repoRoot ? path.join(repoRoot, "Scripts") : null,
    repoRoot ? path.join(repoRoot, "Scripts", "recipes") : null,
    extensionRoot,
    extensionRoot ? path.join(extensionRoot, "Scripts") : null,
  ]);
}

function buildIncludeSearchRootsForSource(
  sourceFilePath: string,
  projectRoot?: string
): string[] {
  const sourceDir = path.dirname(sourceFilePath);
  return uniquePaths([
    sourceDir,
    path.join(sourceDir, ".."),
    path.join(sourceDir, "..", "lib"),
    ...buildIncludeSearchRoots(projectRoot),
  ]);
}

function isAbsoluteIncludePath(includePath: string): boolean {
  return (
    /^(\/|[A-Za-z]:[\\/])/.test(includePath) ||
    includePath.indexOf("file://") === 0
  );
}

function rewriteIncludeDirectives(
  scriptContent: string,
  projectRoot?: string,
  searchRoots?: string[]
): { scriptContent: string; rewritten: string[]; unresolved: string[] } {
  if (!fs) {
    return { scriptContent, rewritten: [], unresolved: [] };
  }

  const roots = searchRoots && searchRoots.length > 0
    ? uniquePaths(searchRoots)
    : buildIncludeSearchRoots(projectRoot);
  const rewritten: string[] = [];
  const unresolved: string[] = [];

  const nextScript = scriptContent.replace(
    /^([ \t]*#include\s+")([^"\r\n]+)("[ \t]*)$/gm,
    (fullMatch, prefix: string, includePath: string, suffix: string) => {
      if (isAbsoluteIncludePath(includePath)) {
        return fullMatch;
      }

      for (let i = 0; i < roots.length; i += 1) {
        const candidate = path.resolve(roots[i], includePath);
        if (!fs.existsSync(candidate)) continue;
        rewritten.push(`${includePath} -> ${candidate}`);
        return prefix + candidate + suffix;
      }

      unresolved.push(includePath);
      return fullMatch;
    }
  );

  return { scriptContent: nextScript, rewritten, unresolved };
}

function extractExternalScriptPath(scriptContent: string): string | null {
  const patterns = [
    /new\s+File\(\s*"([^"\r\n]+\.jsx(?:inc)?)"\s*\)/i,
    /\$\.evalFile\(\s*"([^"\r\n]+\.jsx(?:inc)?)"\s*\)/i,
  ];

  for (let i = 0; i < patterns.length; i += 1) {
    const match = scriptContent.match(patterns[i]);
    if (!match || !match[1]) continue;
    return match[1];
  }

  return null;
}

function expandExternalScriptReference(
  scriptContent: string,
  projectRoot?: string
): {
  scriptContent: string;
  sourcePath?: string;
  rewritten: string[];
  unresolved: string[];
} {
  if (!fs) {
    return { scriptContent, rewritten: [], unresolved: [] };
  }

  const externalPath = extractExternalScriptPath(scriptContent);
  if (!externalPath || !path.isAbsolute(externalPath) || !fs.existsSync(externalPath)) {
    return { scriptContent, rewritten: [], unresolved: [] };
  }

  try {
    const externalSource = fs.readFileSync(externalPath, "utf8");
    const includeRewrite = rewriteIncludeDirectives(
      externalSource.trim(),
      projectRoot,
      buildIncludeSearchRootsForSource(externalPath, projectRoot)
    );

    return {
      scriptContent: includeRewrite.scriptContent,
      sourcePath: externalPath,
      rewritten: includeRewrite.rewritten,
      unresolved: includeRewrite.unresolved,
    };
  } catch {
    return { scriptContent, rewritten: [], unresolved: [] };
  }
}

function prepareRunnableScript(
  scriptContent: string,
  projectRoot?: string
): {
  scriptContent: string;
  expandedSourcePath?: string;
  rewritten: string[];
  unresolved: string[];
} {
  const expanded = expandExternalScriptReference(scriptContent.trim(), projectRoot);
  const includeRewrite = rewriteIncludeDirectives(expanded.scriptContent, projectRoot);

  const exprRewrite = prepareExpressionCapture(includeRewrite.scriptContent);

  if (exprRewrite.rewriteCount > 0) {
    console.log(
      "[AI Action] Rewrote " + exprRewrite.rewriteCount + " expression assignment(s) for runtime error capture."
    );
  }

  return {
    scriptContent: exprRewrite.content,
    expandedSourcePath: expanded.sourcePath,
    rewritten: expanded.rewritten.concat(includeRewrite.rewritten),
    unresolved: expanded.unresolved.concat(includeRewrite.unresolved),
  };
}

function toSummary(displayText: string): string {
  const firstLine = displayText
    .split("\n")
    .map((line) => line.trim())
    .find(Boolean);

  return firstLine || "AI Action ready";
}

function parseErrorLineNumber(errorString: string, errorLine?: number): number | null {
  if (typeof errorLine === "number" && Number.isInteger(errorLine) && errorLine > 0) {
    return errorLine;
  }

  const patterns = [/\(line (\d+)\)/i, /Line:\s*(\d+)/i, /at line (\d+)/i];
  for (const pattern of patterns) {
    const match = errorString.match(pattern);
    if (!match) continue;

    const parsed = Number.parseInt(match[1], 10);
    if (Number.isInteger(parsed) && parsed > 0) {
      return parsed;
    }
  }

  return null;
}

function formatScriptLines(lines: string[], startLine = 1): string {
  return lines
    .map((line, index) => `${startLine + index}: ${line}`)
    .join("\n");
}

export function parseAiActionResponse(content: string): ParsedAiActionResponse {
  const AI_ACTION_REGEX = /<ai-action(?:\s+run="(true|false)")?>([\s\S]*?)<\/ai-action>/gi;
  const matches: RegExpExecArray[] = [];
  let m: RegExpExecArray | null;
  while ((m = AI_ACTION_REGEX.exec(content)) !== null) {
    matches.push(m);
  }

  if (matches.length === 0) {
    return {
      displayText: content.trim(),
      runImmediately: false,
    };
  }

  const first = matches[0];
  const runImmediately = (first[1] || "").toLowerCase() === "true";
  const scriptContent = first[2].trim();
  const validation = scriptContent ? validateScript(scriptContent) : undefined;

  // Remove all ai-action blocks from the display text
  const displayText = content
    .replace(/<ai-action(?:\s+run="(?:true|false)")?>([\s\S]*?)<\/ai-action>/gi, "")
    .trim();

  return {
    displayText: displayText || "AI Action updated.",
    scriptContent: scriptContent || undefined,
    runImmediately,
    multipleBlocks: matches.length > 1,
    validation,
  };
}

export interface ActionRisk {
  risky: boolean;
  reasons: string[];
}

// High-signal ExtendScript APIs that reach outside normal AE editing — file
// system, network, system commands, or dynamic code. A generated creative
// action never needs these, so their presence is the strongest indicator that
// untrusted project content (names, markers, expressions) steered the model
// into emitting something that should not auto-run without a human look.
const RISK_PATTERNS: { pattern: RegExp; reason: string }[] = [
  // ExtendScript allows the constructor with or without `new` (File('~/x'),
  // Folder('~/x')), so match the bare-call form too or the gate is bypassable.
  { pattern: /\bnew\s+File\b|\bFile\s*\(/, reason: "accesses the file system" },
  { pattern: /\bnew\s+Folder\b|\bFolder\s*\(/, reason: "accesses the file system" },
  { pattern: /\bnew\s+Socket\b/, reason: "opens a network connection" },
  { pattern: /\bsystem\s*\.\s*callSystem\b/, reason: "runs a system shell command" },
  { pattern: /\$\s*\.\s*evalFile\b/, reason: "evaluates external code" },
  { pattern: /\beval\s*\(/, reason: "evaluates code dynamically" },
  { pattern: /\bapp\s*\.\s*executeCommand\b/, reason: "runs an arbitrary AE menu command" },
  { pattern: /\bapp\s*\.\s*quit\b/, reason: "quits After Effects" },
];

export function scanActionRisk(script?: string): ActionRisk {
  if (!script) return { risky: false, reasons: [] };
  const reasons: string[] = [];
  for (const { pattern, reason } of RISK_PATTERNS) {
    if (pattern.test(script) && reasons.indexOf(reason) === -1) {
      reasons.push(reason);
    }
  }
  return { risky: reasons.length > 0, reasons };
}

export function clearAiAction(projectRoot?: string): string | null {
  if (!fs) return null;

  const paths = resolveAiActionPaths(projectRoot);
  if (!paths) return null;

  try {
    if (fs.existsSync(paths.scriptPath)) {
      fs.unlinkSync(paths.scriptPath);
    }
    if (fs.existsSync(paths.metaPath)) {
      fs.unlinkSync(paths.metaPath);
    }
  } catch (err: any) {
    return err?.message || String(err);
  }

  return null;
}

export function hasAiAction(projectRoot?: string): boolean {
  if (!fs) return false;

  const paths = resolveAiActionPaths(projectRoot);
  if (!paths) return false;

  return fs.existsSync(paths.scriptPath);
}

export function readAiActionScript(projectRoot?: string): string | null {
  if (!fs) return null;

  const paths = resolveAiActionPaths(projectRoot);
  if (!paths || !fs.existsSync(paths.scriptPath)) return null;

  try {
    return fs.readFileSync(paths.scriptPath, "utf8");
  } catch {
    return null;
  }
}

export function annotateScriptWithError(
  script: string,
  errorString: string,
  errorLine?: number
): string {
  const lines = script.split(/\r?\n/);
  const resolvedLine = parseErrorLineNumber(errorString, errorLine);

  if (
    typeof resolvedLine === "number" &&
    Number.isInteger(resolvedLine) &&
    resolvedLine >= 1 &&
    resolvedLine <= lines.length
  ) {
    const targetIndex = resolvedLine - 1;
    const annotatedLines = [...lines];
    const targetLine = annotatedLines[targetIndex] || "";
    annotatedLines[targetIndex] = targetLine.trim().length > 0
      ? `${targetLine}  // <-- ERROR HERE`
      : "// <-- ERROR HERE";

    const startIndex = Math.max(0, targetIndex - 5);
    const endIndex = Math.min(annotatedLines.length, targetIndex + 6);
    return formatScriptLines(
      annotatedLines.slice(startIndex, endIndex),
      startIndex + 1
    );
  }

  return formatScriptLines(lines.slice(0, 100));
}

export function saveAiAction(
  projectRoot: string | undefined,
  scriptContent: string,
  displayText: string
): AiActionState {
  if (!fs) {
    throw new Error("Node.js filesystem access is unavailable.");
  }

  const paths = resolveAiActionPaths(projectRoot);
  if (!paths) {
    throw new Error("AI Action storage could not be resolved from the extension path.");
  }

  ensureActionDir(paths.actionDir);

  const summary = toSummary(displayText);
  const prepared = prepareRunnableScript(scriptContent.trim(), projectRoot);
  const scriptText = buildScriptHeader(summary) + prepared.scriptContent + "\n";
  const updatedAt = new Date().toISOString();

  const preview = prepared.scriptContent.substring(0, 500);
  console.log(
    "[AI Action] Writing script (" + prepared.scriptContent.length + " chars):\n" +
    preview + (prepared.scriptContent.length > 500 ? "\n..." : "")
  );
  if (prepared.rewritten.length > 0) {
    console.log(
      "[AI Action] Rewrote #include directives:\n" + prepared.rewritten.join("\n")
    );
  }
  if (prepared.expandedSourcePath) {
    console.log("[AI Action] Expanded external script reference: " + prepared.expandedSourcePath);
  }
  if (prepared.unresolved.length > 0) {
    console.warn(
      "[AI Action] Unresolved #include directives:\n" + prepared.unresolved.join("\n")
    );
  }

  fs.writeFileSync(paths.scriptPath, scriptText, "utf8");
  fs.writeFileSync(
    paths.metaPath,
    JSON.stringify({ summary, updatedAt }, null, 2),
    "utf8"
  );

  return {
    scriptPath: paths.scriptPath,
    metaPath: paths.metaPath,
    summary,
    updatedAt,
  };
}

export async function runAiAction(projectRoot?: string) {
  if (!hasAiAction(projectRoot)) {
    throw new Error("No AI Action is currently loaded.");
  }

  const paths = resolveAiActionPaths(projectRoot);
  if (!paths) {
    throw new Error("AI Action storage could not be resolved from the extension path.");
  }

  // Security guard: ensure the script path is inside the .session/ directory.
  // resolveAiActionPaths always builds this path, but we validate explicitly as
  // defense-in-depth in case the calling context changes in the future.
  const resolvedScript = path.resolve(paths.scriptPath);
  const resolvedDir = path.resolve(paths.actionDir);
  if (!resolvedScript.startsWith(resolvedDir + path.sep)) {
    throw new Error("AI Action path is outside the session directory.");
  }

  if (fs.existsSync(paths.scriptPath)) {
    try {
      const currentScript = fs.readFileSync(paths.scriptPath, "utf8");
      const prepared = prepareRunnableScript(currentScript, projectRoot);
      const normalizedCurrent = currentScript.replace(/\r\n/g, "\n").trim();
      const normalizedPrepared = prepared.scriptContent.replace(/\r\n/g, "\n").trim();

      if (normalizedPrepared && normalizedPrepared !== normalizedCurrent) {
        console.log("[AI Action] Refreshing stored runnable script before execution.");
        if (prepared.expandedSourcePath) {
          console.log(
            "[AI Action] Expanded external script reference: " + prepared.expandedSourcePath
          );
        }
        if (prepared.rewritten.length > 0) {
          console.log(
            "[AI Action] Rewrote #include directives:\n" + prepared.rewritten.join("\n")
          );
        }
        if (prepared.unresolved.length > 0) {
          console.warn(
            "[AI Action] Unresolved #include directives:\n" + prepared.unresolved.join("\n")
          );
        }
        fs.writeFileSync(paths.scriptPath, normalizedPrepared + "\n", "utf8");
      }
    } catch (err) {
      console.warn("[AI Action] Failed to refresh runnable script: " + String(err));
    }
  }

  return await evalTS("runScriptFile", paths.scriptPath);
}

export function getAiActionScriptPath(projectRoot?: string): string | null {
  if (!fs) return null;
  const paths = resolveAiActionPaths(projectRoot);
  if (!paths) return null;
  return fs.existsSync(paths.scriptPath) ? paths.scriptPath : null;
}

export function revealAiActionInFinder(
  projectRoot?: string
): { ok: boolean; error?: string } {
  const scriptPath = getAiActionScriptPath(projectRoot);
  if (!scriptPath) {
    return { ok: false, error: "No AI Action script found." };
  }
  if (!os || os.platform() !== "darwin") {
    return { ok: false, error: "Reveal in Finder is only available on macOS." };
  }
  try {
    child_process
      .spawn("open", ["-R", scriptPath], { detached: true, stdio: "ignore" })
      .unref();
    return { ok: true };
  } catch (err: any) {
    return { ok: false, error: err?.message || String(err) };
  }
}
